Path: news.gmane.org!not-for-mail
From: Ralf Madorf <ralf.mardorf@alice-dsl.net>
Newsgroups: gmane.linux.arch.general
Subject: [Thread closed] Is there a clean solution to get
 completely rid of Pulseaudio?
Date: Sat, 24 Dec 2011 09:25:41 +0100
Lines: 37
Approved: news@gmane.org
Message-ID: <1324715141.1216.76.camel@localhost.localdomain>
References: <1324629697.9930.38.camel@localhost.localdomain>
 <4EF44735.8050009@archlinux.org>
 <1324632316.9930.45.camel@localhost.localdomain>
 <4EF44980.8060609@archlinux.org>
 <CA+4o_oGk94pCMKLAfTy8Eagz3ty=qf3+tJ==AhvzSwuUMWg_Eg@mail.gmail.com>
 <1324634614.9930.75.camel@localhost.localdomain>
 <4EF54857.4010008@brendanlong.com>
 <1324710528.1216.44.camel@localhost.localdomain>
 <CAGAVQTGtuB3Xz1HEpZWbR3QwK_ASMyP10TCq6xvUtH5vb+=qFg@mail.gmail.com>
Reply-To: General Discussion about Arch Linux <arch-general@archlinux.org>
NNTP-Posting-Host: lo.gmane.org
Mime-Version: 1.0
Content-Type: text/plain; charset="UTF-8"
Content-Transfer-Encoding: 7bit
X-Trace: dough.gmane.org 1324715153 3128 80.91.229.12 (24 Dec 2011 08:25:53 GMT)
X-Complaints-To: usenet@dough.gmane.org
NNTP-Posting-Date: Sat, 24 Dec 2011 08:25:53 +0000 (UTC)
To: arch-general@archlinux.org
Original-X-From: arch-general-bounces@archlinux.org Sat Dec 24 09:25:50 2011
Return-path: <arch-general-bounces@archlinux.org>
Envelope-to: glag-arch@m.gmane.org
Original-Received: from gerolde.archlinux.org ([66.211.214.132])
	by lo.gmane.org with esmtp (Exim 4.69)
	(envelope-from <arch-general-bounces@archlinux.org>)
	id 1ReMvN-0005Gt-F4
	for glag-arch@m.gmane.org; Sat, 24 Dec 2011 09:25:49 +0100
Original-Received: from gudrun.archlinux.org (gudrun.archlinux.org [66.211.214.131])
	by gerolde.archlinux.org (Postfix) with ESMTP id 25DEF90176;
	Sat, 24 Dec 2011 03:25:44 -0500 (EST)
Original-Received: from gerolde.archlinux.org (gerolde.archlinux.org [66.211.214.132])
 by gudrun.archlinux.org (Postfix) with ESMTP id 6F31A86164
 for <arch-general@archlinux.org>; Sat, 24 Dec 2011 03:25:42 -0500 (EST)
Received-SPF: none (alice-dsl.net: No applicable sender policy available)
 receiver=gerolde.archlinux.org; identity=mailfrom;
 envelope-from="ralf.mardorf@alice-dsl.net"; helo=smtp-out01.alice-dsl.net;
 client-ip=88.44.60.11
Original-Received: from smtp-out01.alice-dsl.net (smtp-out01.alice-dsl.net
 [88.44.60.11])
 by gerolde.archlinux.org (Postfix) with ESMTP id 1A9C490174
 for <arch-general@archlinux.org>; Sat, 24 Dec 2011 03:25:41 -0500 (EST)
Original-Received: from out.alice-dsl.de ([192.168.124.120]) by
 smtp-out01.alice-dsl.net with Microsoft SMTPSVC(6.0.3790.3959); 
 Sat, 24 Dec 2011 09:25:42 +0100
Original-Received: from [92.231.5.64] ([92.231.5.64]) by out.alice-dsl.de over TLS
 secured channel with Microsoft SMTPSVC(6.0.3790.3959); 
 Sat, 24 Dec 2011 09:25:42 +0100
In-Reply-To: <CAGAVQTGtuB3Xz1HEpZWbR3QwK_ASMyP10TCq6xvUtH5vb+=qFg@mail.gmail.com>
X-Mailer: Evolution 3.2.2 
X-OriginalArrivalTime: 24 Dec 2011 08:25:42.0310 (UTC)
 FILETIME=[A01A9460:01CCC215]
X-BeenThere: arch-general@archlinux.org
X-Mailman-Version: 2.1.14
Precedence: list
List-Id: General Discussion about Arch Linux <arch-general.archlinux.org>
List-Unsubscribe: <http://mailman.archlinux.org/mailman/options/arch-general>, 
 <mailto:arch-general-request@archlinux.org?subject=unsubscribe>
List-Archive: <http://mailman.archlinux.org/pipermail/arch-general>
List-Post: <mailto:arch-general@archlinux.org>
List-Help: <mailto:arch-general-request@archlinux.org?subject=help>
List-Subscribe: <http://mailman.archlinux.org/mailman/listinfo/arch-general>, 
 <mailto:arch-general-request@archlinux.org?subject=subscribe>
Errors-To: arch-general-bounces@archlinux.org
Original-Sender: arch-general-bounces@archlinux.org
Xref: news.gmane.org gmane.linux.arch.general:38453
Archived-At: <http://permalink.gmane.org/gmane.linux.arch.general/38453>

On Sat, 2011-12-24 at 01:49 -0600, C Anthony Risinger wrote:
> Ralf ...
> 
> your thread has managed to generate 65+ responses in 24 hours [snip]

Most of them were unfriendly insults by others! So please be fair and
don't blame me. You might count the useful friendly mails instead.
Btw. it's not only me who was abused without a reason.

When somebody asked regarding to the upgrade mtab issue it also caused a
flood of unneeded mails. Instead of posting a link to the latest news
http://www.archlinux.org/ on this list it seems to be netiquette to
insult users. It was the same with somebody asking regarding to
locale.sh, about people who do top posting etc. ... FWIW I got help
regarding to this thread from top posters :).

> conjectures regarding PulseAudio

I experienced enough issues myself and several Linux audio users lists
are crowded with issues regarding to PA.

> i thoroughly recommend immediately and permanently terminating this
> line of conversation, and returning when you have encountered a
> _concrete_ problem by which PulseAudio is [seemingly] causing an
> immediate, and diagnosable, issue, and you are unable to solve it via
> the usuals (eg. wiki, bbs, GOOG) ... else, i suspect your ability to
> procure future solutions from this list, and your peers, will be
> hampered by the impression being formed right now.
> 
> take it or leave it :-)

I'll replace PA by a dummy package, hence it won't cause trouble on my
machine. Thread closed!

- Ralf


