Path: news.gmane.org!not-for-mail
From: Ralf Madorf <ralf.mardorf@alice-dsl.net>
Newsgroups: gmane.linux.arch.general
Subject: Re: Is there a clean solution to get completely rid
 of Pulseaudio?
Date: Fri, 23 Dec 2011 11:35:49 +0100
Lines: 26
Approved: news@gmane.org
Message-ID: <1324636549.10606.113.camel@localhost.localdomain>
References: <1324629697.9930.38.camel@localhost.localdomain>
 <CAGAVQTFKQxo4a2Bjg8nBPyjE+Ue5QKNdB1y8A8WjOXbMBjX49w@mail.gmail.com>
 <1324635069.10606.9.camel@localhost.localdomain>
 <CAD+HWv9=rsE+aDkfsriieP07_RAYY5LSPdi51KtjdbT2vqwWYA@mail.gmail.com>
Reply-To: General Discussion about Arch Linux <arch-general@archlinux.org>
NNTP-Posting-Host: lo.gmane.org
Mime-Version: 1.0
Content-Type: text/plain; charset="UTF-8"
Content-Transfer-Encoding: 7bit
X-Trace: dough.gmane.org 1324636569 1247 80.91.229.12 (23 Dec 2011 10:36:09 GMT)
X-Complaints-To: usenet@dough.gmane.org
NNTP-Posting-Date: Fri, 23 Dec 2011 10:36:09 +0000 (UTC)
To: arch-general@archlinux.org
Original-X-From: arch-general-bounces@archlinux.org Fri Dec 23 11:36:05 2011
Return-path: <arch-general-bounces@archlinux.org>
Envelope-to: glag-arch@m.gmane.org
Original-Received: from gerolde.archlinux.org ([66.211.214.132])
	by lo.gmane.org with esmtp (Exim 4.69)
	(envelope-from <arch-general-bounces@archlinux.org>)
	id 1Re2Ts-000337-4T
	for glag-arch@m.gmane.org; Fri, 23 Dec 2011 11:36:04 +0100
Original-Received: from gudrun.archlinux.org (gudrun.archlinux.org [66.211.214.131])
	by gerolde.archlinux.org (Postfix) with ESMTP id 8FC5590137;
	Fri, 23 Dec 2011 05:36:00 -0500 (EST)
Original-Received: from gerolde.archlinux.org (gerolde.archlinux.org [66.211.214.132])
 by gudrun.archlinux.org (Postfix) with ESMTP id 9F46086163
 for <arch-general@archlinux.org>; Fri, 23 Dec 2011 05:35:58 -0500 (EST)
Received-SPF: none (alice-dsl.net: No applicable sender policy available)
 receiver=gerolde.archlinux.org; identity=mailfrom;
 envelope-from="ralf.mardorf@alice-dsl.net"; helo=smtp-out02.alice-dsl.net;
 client-ip=88.44.60.12
Original-Received: from smtp-out02.alice-dsl.net (smtp-out02.alice-dsl.net
 [88.44.60.12])
 by gerolde.archlinux.org (Postfix) with ESMTP id 6530590130
 for <arch-general@archlinux.org>; Fri, 23 Dec 2011 05:35:57 -0500 (EST)
Original-Received: from out.alice-dsl.de ([192.168.125.59]) by smtp-out02.alice-dsl.net
 with Microsoft SMTPSVC(6.0.3790.3959); 
 Fri, 23 Dec 2011 11:35:58 +0100
Original-Received: from [85.182.18.151] ([85.182.18.151]) by out.alice-dsl.de over TLS
 secured channel with Microsoft SMTPSVC(6.0.3790.3959); 
 Fri, 23 Dec 2011 11:35:49 +0100
In-Reply-To: <CAD+HWv9=rsE+aDkfsriieP07_RAYY5LSPdi51KtjdbT2vqwWYA@mail.gmail.com>
X-Mailer: Evolution 3.2.2 
X-OriginalArrivalTime: 23 Dec 2011 10:35:50.0036 (UTC)
 FILETIME=[A3754540:01CCC15E]
X-BeenThere: arch-general@archlinux.org
X-Mailman-Version: 2.1.14
Precedence: list
List-Id: General Discussion about Arch Linux <arch-general.archlinux.org>
List-Unsubscribe: <http://mailman.archlinux.org/mailman/options/arch-general>, 
 <mailto:arch-general-request@archlinux.org?subject=unsubscribe>
List-Archive: <http://mailman.archlinux.org/pipermail/arch-general>
List-Post: <mailto:arch-general@archlinux.org>
List-Help: <mailto:arch-general-request@archlinux.org?subject=help>
List-Subscribe: <http://mailman.archlinux.org/mailman/listinfo/arch-general>, 
 <mailto:arch-general-request@archlinux.org?subject=subscribe>
Errors-To: arch-general-bounces@archlinux.org
Original-Sender: arch-general-bounces@archlinux.org
Xref: news.gmane.org gmane.linux.arch.general:38386
Archived-At: <http://permalink.gmane.org/gmane.linux.arch.general/38386>

Wow :D

I first just asked for a solution similar to Debian dummy packages and
get tons [1] of insults.

Then I explained why I (and I know a lot of other people) will install
e.g. GNOME. I'll do it again. We might wish to use this DE or simply GDM
as login manager. I don't blame Arch Linux packages, I just blame
answers like "don't use gnome".

No netiquette?

I was silent since days, stopped putting in my 2 cents all the time and
now I asked for help and get those answers?! That's strange and creepy.

Anyway, if somebody should know a solution how to use GNOME without PA,
any hints are welcome.

Cheers!

Ralf

[1] OT, but too funny, since I got all mails two times, even more than
1k of old mails Evolution already had downloaded from the server.


