Path: news.gmane.org!not-for-mail
From: Ralf Madorf <ralf.mardorf@alice-dsl.net>
Newsgroups: gmane.linux.arch.general
Subject: Re: Is there a clean solution to get completely rid
 of Pulseaudio?
Date: Fri, 23 Dec 2011 10:57:40 +0100
Lines: 17
Approved: news@gmane.org
Message-ID: <1324634260.9930.71.camel@localhost.localdomain>
References: <1324629697.9930.38.camel@localhost.localdomain>
 <4EF44735.8050009@archlinux.org>
 <1324632316.9930.45.camel@localhost.localdomain>
 <4EF44980.8060609@archlinux.org>
 <CAD5P+LZG6X=XmJYzBvn35wqAy9UQx9LWUvi6Anv_CLEGR7zmmw@mail.gmail.com>
Reply-To: General Discussion about Arch Linux <arch-general@archlinux.org>
NNTP-Posting-Host: lo.gmane.org
Mime-Version: 1.0
Content-Type: text/plain; charset="UTF-8"
Content-Transfer-Encoding: 7bit
X-Trace: dough.gmane.org 1324634275 18588 80.91.229.12 (23 Dec 2011 09:57:55 GMT)
X-Complaints-To: usenet@dough.gmane.org
NNTP-Posting-Date: Fri, 23 Dec 2011 09:57:55 +0000 (UTC)
To: arch-general@archlinux.org
Original-X-From: arch-general-bounces@archlinux.org Fri Dec 23 10:57:51 2011
Return-path: <arch-general-bounces@archlinux.org>
Envelope-to: glag-arch@m.gmane.org
Original-Received: from gerolde.archlinux.org ([66.211.214.132])
	by lo.gmane.org with esmtp (Exim 4.69)
	(envelope-from <arch-general-bounces@archlinux.org>)
	id 1Re1sr-0000sY-Vv
	for glag-arch@m.gmane.org; Fri, 23 Dec 2011 10:57:50 +0100
Original-Received: from gudrun.archlinux.org (gudrun.archlinux.org [66.211.214.131])
	by gerolde.archlinux.org (Postfix) with ESMTP id DBAD590099;
	Fri, 23 Dec 2011 04:57:46 -0500 (EST)
Original-Received: from gerolde.archlinux.org (gerolde.archlinux.org [66.211.214.132])
 by gudrun.archlinux.org (Postfix) with ESMTP id ED7EF86163
 for <arch-general@archlinux.org>; Fri, 23 Dec 2011 04:57:45 -0500 (EST)
Received-SPF: none (alice-dsl.net: No applicable sender policy available)
 receiver=gerolde.archlinux.org; identity=mailfrom;
 envelope-from="ralf.mardorf@alice-dsl.net"; helo=smtp-out03.alice-dsl.net;
 client-ip=88.44.63.5
Original-Received: from smtp-out03.alice-dsl.net (smtp-out03.alice-dsl.net [88.44.63.5])
 by gerolde.archlinux.org (Postfix) with ESMTP id A867990091
 for <arch-general@archlinux.org>; Fri, 23 Dec 2011 04:57:45 -0500 (EST)
Original-Received: from out.alice-dsl.de ([192.168.125.60]) by smtp-out03.alice-dsl.net
 with Microsoft SMTPSVC(6.0.3790.3959); 
 Fri, 23 Dec 2011 10:57:46 +0100
Original-Received: from [85.182.18.151] ([85.182.18.151]) by out.alice-dsl.de over TLS
 secured channel with Microsoft SMTPSVC(6.0.3790.3959); 
 Fri, 23 Dec 2011 10:57:40 +0100
In-Reply-To: <CAD5P+LZG6X=XmJYzBvn35wqAy9UQx9LWUvi6Anv_CLEGR7zmmw@mail.gmail.com>
X-Mailer: Evolution 3.2.2 
X-OriginalArrivalTime: 23 Dec 2011 09:57:40.0770 (UTC)
 FILETIME=[4EF30020:01CCC159]
X-BeenThere: arch-general@archlinux.org
X-Mailman-Version: 2.1.14
Precedence: list
List-Id: General Discussion about Arch Linux <arch-general.archlinux.org>
List-Unsubscribe: <http://mailman.archlinux.org/mailman/options/arch-general>, 
 <mailto:arch-general-request@archlinux.org?subject=unsubscribe>
List-Archive: <http://mailman.archlinux.org/pipermail/arch-general>
List-Post: <mailto:arch-general@archlinux.org>
List-Help: <mailto:arch-general-request@archlinux.org?subject=help>
List-Subscribe: <http://mailman.archlinux.org/mailman/listinfo/arch-general>, 
 <mailto:arch-general-request@archlinux.org?subject=subscribe>
Errors-To: arch-general-bounces@archlinux.org
Original-Sender: arch-general-bounces@archlinux.org
Xref: news.gmane.org gmane.linux.arch.general:38370
Archived-At: <http://permalink.gmane.org/gmane.linux.arch.general/38370>

On Fri, 2011-12-23 at 13:02 +0330, ali.mousavi@gmail.com wrote:
> you can't use gnome 3 without pulse audio. if you don't want to use pulse
> audio, consider using another DE or WM.

At the moment I'm using Xfce only, but I will have the libre to use
GNOME3 too, since it works without PA. It did work without PA for my
Debian.

As mentioned before, at the moment only GDM is installed.

Btw. for what tasks PA is needed? I don't know any task that's relevant
for a DAW. But having the libre to use every DE for a DAW should be
possible.

- Ralf


