Path: news.gmane.org!not-for-mail
From: Ralf Madorf <ralf.mardorf@alice-dsl.net>
Newsgroups: gmane.linux.arch.general
Subject: Is there a clean solution to get completely rid of
	Pulseaudio?
Date: Fri, 23 Dec 2011 09:41:37 +0100
Lines: 46
Approved: news@gmane.org
Message-ID: <1324629697.9930.38.camel@localhost.localdomain>
Reply-To: General Discussion about Arch Linux <arch-general@archlinux.org>
NNTP-Posting-Host: lo.gmane.org
Mime-Version: 1.0
Content-Type: text/plain; charset="UTF-8"
Content-Transfer-Encoding: 7bit
X-Trace: dough.gmane.org 1324629717 22778 80.91.229.12 (23 Dec 2011 08:41:57 GMT)
X-Complaints-To: usenet@dough.gmane.org
NNTP-Posting-Date: Fri, 23 Dec 2011 08:41:57 +0000 (UTC)
To: General Discussion about Arch Linux <arch-general@archlinux.org>
Original-X-From: arch-general-bounces@archlinux.org Fri Dec 23 09:41:52 2011
Return-path: <arch-general-bounces@archlinux.org>
Envelope-to: glag-arch@m.gmane.org
Original-Received: from gerolde.archlinux.org ([66.211.214.132])
	by lo.gmane.org with esmtp (Exim 4.69)
	(envelope-from <arch-general-bounces@archlinux.org>)
	id 1Re0hM-0008BB-8j
	for glag-arch@m.gmane.org; Fri, 23 Dec 2011 09:41:52 +0100
Original-Received: from gudrun.archlinux.org (gudrun.archlinux.org [66.211.214.131])
	by gerolde.archlinux.org (Postfix) with ESMTP id 9A7229006D;
	Fri, 23 Dec 2011 03:41:47 -0500 (EST)
Original-Received: from gerolde.archlinux.org (gerolde.archlinux.org [66.211.214.132])
 by gudrun.archlinux.org (Postfix) with ESMTP id 8093986163
 for <arch-general@archlinux.org>; Fri, 23 Dec 2011 03:41:45 -0500 (EST)
Received-SPF: none (alice-dsl.net: No applicable sender policy available)
 receiver=gerolde.archlinux.org; identity=mailfrom;
 envelope-from="ralf.mardorf@alice-dsl.net"; helo=smtp-out01.alice-dsl.net;
 client-ip=88.44.60.11
Original-Received: from smtp-out01.alice-dsl.net (smtp-out01.alice-dsl.net
 [88.44.60.11])
 by gerolde.archlinux.org (Postfix) with ESMTP id 2EA6F90069
 for <arch-general@archlinux.org>; Fri, 23 Dec 2011 03:41:44 -0500 (EST)
Original-Received: from out.alice-dsl.de ([192.168.124.118]) by
 smtp-out01.alice-dsl.net with Microsoft SMTPSVC(6.0.3790.3959); 
 Fri, 23 Dec 2011 09:41:44 +0100
Original-Received: from [85.182.18.151] ([85.182.18.151]) by out.alice-dsl.de over TLS
 secured channel with Microsoft SMTPSVC(6.0.3790.3959); 
 Fri, 23 Dec 2011 09:41:45 +0100
X-Mailer: Evolution 3.2.2 
X-OriginalArrivalTime: 23 Dec 2011 08:41:45.0203 (UTC)
 FILETIME=[B39EA430:01CCC14E]
X-BeenThere: arch-general@archlinux.org
X-Mailman-Version: 2.1.14
Precedence: list
List-Id: General Discussion about Arch Linux <arch-general.archlinux.org>
List-Unsubscribe: <http://mailman.archlinux.org/mailman/options/arch-general>, 
 <mailto:arch-general-request@archlinux.org?subject=unsubscribe>
List-Archive: <http://mailman.archlinux.org/pipermail/arch-general>
List-Post: <mailto:arch-general@archlinux.org>
List-Help: <mailto:arch-general-request@archlinux.org?subject=help>
List-Subscribe: <http://mailman.archlinux.org/mailman/listinfo/arch-general>, 
 <mailto:arch-general-request@archlinux.org?subject=subscribe>
Errors-To: arch-general-bounces@archlinux.org
Original-Sender: arch-general-bounces@archlinux.org
Xref: news.gmane.org gmane.linux.arch.general:38355
Archived-At: <http://permalink.gmane.org/gmane.linux.arch.general/38355>

Hi :)

people told me that Arch Linux will not force me to install PA. Today I
continued to set up my Arch Linux. A cold still hinder me to work very
long on my computer, so until now Google didn't help me to find an easy
solution to get rid of PA. Arch Linux on my machine does force me to
install PA to keep the system consistent.

I found this information:
https://bbs.archlinux.org/viewtopic.php?pid=998489#p998489

I already read tons of irrelevant comments similar to
https://bbs.archlinux.org/viewtopic.php?pid=998290#p998290

Even no information on
https://wiki.archlinux.org/index.php/Pro_Audio

I like using Google and reading Wikis, in spite of my dyslexia. I don't
like to read tons of irrelevant stuff to find out, that in the end
there's no clean solution.

Is there a clean solution to get completely rid of PA?

PA for my needs is absolutely obstructive.

I try to set up a DAW using two Terratec EWX 24/96 for MIDI only (but
both are audio devices too) and for audio a RME HDSPe. The only thing PA
will do for me, is causing trouble.

IIRC on Debian I got rid of PA by replacing 2 packages by empty dummy
packages, then everything was ok. I figured this out my self. Btw. for
Debian it was the same, people told me that Debian doesn't force to use
PA, but it does.

Since I'm new to Arch Linux I need some information. May I ask where I
get the needed information to completely once and for all get rid of PA?

TIA,

Ralf

PS: There are reasons to get rid of PA. The "installing PA isn't
absolutely obstructive" crowd might use Google, IIRC there e.g. was the
description of an issue in an Ubuntu Studio mailing list this month.


