Path: news.gmane.org!not-for-mail
From: Dieter Plaetinck <dieter-7FYLOmueu/EUehRvb1n7cg@public.gmane.org>
Newsgroups: gmane.linux.arch.releng
Subject: Re: Arch Linux Official Installation Guide in git
Date: Mon, 26 Dec 2011 17:00:20 +0100
Lines: 16
Approved: news@gmane.org
Message-ID: <20111226170020.42c2d4d5@plaetinck.be>
References: <CAO0v=MPT2VmKej3AQdNcqkGUzb_vAdSVaKt_kzH-8SNqJbxXZw@mail.gmail.com>
Reply-To: Arch Linux Release Engineering <arch-releng-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>
NNTP-Posting-Host: lo.gmane.org
Mime-Version: 1.0
Content-Type: text/plain; charset=US-ASCII
Content-Transfer-Encoding: 7bit
X-Trace: dough.gmane.org 1324915284 24260 80.91.229.12 (26 Dec 2011 16:01:24 GMT)
X-Complaints-To: usenet@dough.gmane.org
NNTP-Posting-Date: Mon, 26 Dec 2011 16:01:24 +0000 (UTC)
To: Arch Linux Release Engineering <arch-releng-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>
Original-X-From: arch-releng-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org Mon Dec 26 17:01:19 2011
Return-path: <arch-releng-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>
Envelope-to: glar-arch-releng@m.gmane.org
Original-Received: from gerolde.archlinux.org ([66.211.214.132])
	by lo.gmane.org with esmtp (Exim 4.69)
	(envelope-from <arch-releng-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>)
	id 1RfCzG-0007oF-Ku
	for glar-arch-releng@m.gmane.org; Mon, 26 Dec 2011 17:01:18 +0100
Original-Received: from gudrun.archlinux.org (gudrun.archlinux.org [66.211.214.131])
	by gerolde.archlinux.org (Postfix) with ESMTP id DFBDA90207;
	Mon, 26 Dec 2011 11:01:14 -0500 (EST)
Original-Received: from gerolde.archlinux.org (gerolde.archlinux.org [66.211.214.132])
 by gudrun.archlinux.org (Postfix) with ESMTP id 9E16C86171
 for <arch-releng-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>; Mon, 26 Dec 2011 11:01:13 -0500 (EST)
Received-SPF: none (plaetinck.be: No applicable sender policy available)
 receiver=gerolde.archlinux.org; identity=mailfrom;
 envelope-from="dieter-7FYLOmueu/EUehRvb1n7cg@public.gmane.org"; helo=smtp.priorweb.be;
 client-ip=62.182.61.111
Original-Received: from smtp.priorweb.be (smtp01.priorweb.be [62.182.61.111])
 by gerolde.archlinux.org (Postfix) with ESMTPS id 8543C90203
 for <arch-releng-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>; Mon, 26 Dec 2011 11:01:13 -0500 (EST)
Original-Received: from [178.79.146.162] (port=53863 helo=localhost.localdomain)
 by smtp.priorweb.be with esmtps (TLS1.0:DHE_RSA_AES_128_CBC_SHA1:16)
 (Exim 4.72) (envelope-from <dieter-7FYLOmueu/EUehRvb1n7cg@public.gmane.org>) id 1RfCzA-0004nA-25
 for arch-releng-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org; Mon, 26 Dec 2011 17:01:12 +0100
In-Reply-To: <CAO0v=MPT2VmKej3AQdNcqkGUzb_vAdSVaKt_kzH-8SNqJbxXZw-JsoAwUIsXosN+BqQ9rBEUg@public.gmane.org>
X-Mailer: Claws Mail 3.8.0 (GTK+ 2.24.8; x86_64-unknown-linux-gnu)
X-BeenThere: arch-releng-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org
X-Mailman-Version: 2.1.14
Precedence: list
List-Id: Arch Linux Release Engineering <arch-releng.archlinux.org>
List-Unsubscribe: <http://mailman.archlinux.org/mailman/options/arch-releng>, 
 <mailto:arch-releng-request-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org?subject=unsubscribe>
List-Archive: <http://mailman.archlinux.org/pipermail/arch-releng>
List-Post: <mailto:arch-releng-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>
List-Help: <mailto:arch-releng-request-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org?subject=help>
List-Subscribe: <http://mailman.archlinux.org/mailman/listinfo/arch-releng>,
 <mailto:arch-releng-request-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org?subject=subscribe>
Errors-To: arch-releng-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org
Original-Sender: arch-releng-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org
Xref: news.gmane.org gmane.linux.arch.releng:960
Archived-At: <http://permalink.gmane.org/gmane.linux.arch.releng/960>

On Mon, 26 Dec 2011 16:41:37 +0100
Karol Blazewicz <karol.blazewicz-Re5JQEeQqe8AvxtiuMwx3w@public.gmane.org> wrote:

> Is
> http://projects.archlinux.org/aif.git/plain/doc/official_installation_guide_en
> the latest version? It says so on
> https://wiki.archlinux.org/index.php/Official_Installation_Guide.
> Will the Official Installation Guide that's in the wiki be updated?

the "latest" is the one in the development branch.
the "latest official" is the one in the master branch.

yes, I'll update it as soon as there's a new release version.

Dieter

