Path: news.gmane.org!not-for-mail
From: speps <speps-KK0ffGbhmjU@public.gmane.org>
Newsgroups: gmane.linux.arch.tur.user
Subject: Merge Request
Date: Sat, 17 Dec 2011 23:32:13 +0100
Lines: 39
Approved: news@gmane.org
Message-ID: <20111217233213.3b906d6c.speps@gmx.com>
Reply-To: "Discussion about the Arch User Repository \(AUR\)"
 <aur-general-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>
NNTP-Posting-Host: lo.gmane.org
Mime-Version: 1.0
Content-Type: multipart/signed; protocol="application/pgp-signature";
 micalg="PGP-SHA1";
 boundary="Signature=_Sat__17_Dec_2011_23_32_13_+0100_r_0jpZWYdIjX9Gde"
X-Trace: dough.gmane.org 1324160792 23299 80.91.229.12 (17 Dec 2011 22:26:32 GMT)
X-Complaints-To: usenet@dough.gmane.org
NNTP-Posting-Date: Sat, 17 Dec 2011 22:26:32 +0000 (UTC)
To: aur-general-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org
Original-X-From: aur-general-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org Sat Dec 17 23:26:28 2011
Return-path: <aur-general-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>
Envelope-to: glatu-tur-users@m.gmane.org
Original-Received: from gerolde.archlinux.org ([66.211.214.132])
	by lo.gmane.org with esmtp (Exim 4.69)
	(envelope-from <aur-general-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>)
	id 1Rc2i3-000577-5A
	for glatu-tur-users@m.gmane.org; Sat, 17 Dec 2011 23:26:27 +0100
Original-Received: from gudrun.archlinux.org (gudrun.archlinux.org [66.211.214.131])
	by gerolde.archlinux.org (Postfix) with ESMTP id 7395490028;
	Sat, 17 Dec 2011 17:26:24 -0500 (EST)
Original-Received: from gerolde.archlinux.org (gerolde.archlinux.org [66.211.214.132])
 by gudrun.archlinux.org (Postfix) with ESMTP id DB6068615D
 for <aur-general-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>; Sat, 17 Dec 2011 17:26:21 -0500 (EST)
Received-SPF: pass (gmx.com: 213.165.64.45 is authorized to use
 'speps-KK0ffGbhmjU@public.gmane.org' in 'mfrom' identity (mechanism 'ip4:213.165.64.0/23'
 matched)) receiver=gerolde.archlinux.org; identity=mailfrom;
 envelope-from="speps-KK0ffGbhmjU@public.gmane.org"; helo=mailout-eu.gmx.com;
 client-ip=213.165.64.45
Original-Received: from mailout-eu.gmx.com (mailout-eu.gmx.com [213.165.64.45])
 by gerolde.archlinux.org (Postfix) with SMTP id 6ED2D90027
 for <aur-general-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>; Sat, 17 Dec 2011 17:26:20 -0500 (EST)
Original-Received: (qmail invoked by alias); 17 Dec 2011 22:26:20 -0000
Original-Received: from unknown (EHLO localhost.localdomain) [151.75.215.187]
 by mail.gmx.com (mp-eu001) with SMTP; 17 Dec 2011 23:26:20 +0100
X-Authenticated: #68454364
X-Provags-ID: V01U2FsdGVkX19uPgJ0W0Nu0jmRSnYv5XpNtt66mRSAQG1HoJABuM
 aWUBg2r3PEpUMp
X-Mailer: Sylpheed 3.1.2 (GTK+ 2.24.8; x86_64-unknown-linux-gnu)
X-Face: '7Y!]\tBO_>:sI_+>]L*U\V.mqk2i"L2)6&b5GntEW8G,;
 0)Dr05mI:&wd9$:,(xwImrY9# Qy3.kLN\ef~+BD:M(Dh+%74rxc#-N[|}UQ=\[w
X-Y-GMX-Trusted: 0
X-BeenThere: aur-general-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org
X-Mailman-Version: 2.1.14
Precedence: list
List-Id: "Discussion about the Arch User Repository \(AUR\)"
 <aur-general.archlinux.org>
List-Unsubscribe: <http://mailman.archlinux.org/mailman/options/aur-general>, 
 <mailto:aur-general-request-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org?subject=unsubscribe>
List-Archive: <http://mailman.archlinux.org/pipermail/aur-general>
List-Post: <mailto:aur-general-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>
List-Help: <mailto:aur-general-request-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org?subject=help>
List-Subscribe: <http://mailman.archlinux.org/mailman/listinfo/aur-general>,
 <mailto:aur-general-request-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org?subject=subscribe>
Errors-To: aur-general-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org
Original-Sender: aur-general-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org
Xref: news.gmane.org gmane.linux.arch.tur.user:23072
Archived-At: <http://permalink.gmane.org/gmane.linux.arch.tur.user/23072>

--Signature=_Sat__17_Dec_2011_23_32_13_+0100_r_0jpZWYdIjX9Gde
Content-Type: text/plain; charset=US-ASCII
Content-Disposition: inline
Content-Transfer-Encoding: quoted-printable

Hi,

a merge is requested:

[1] zope-event     -> [2] python2-zope-event
[3] zope-component -> [4] python2-zope-component

Tnx


[1] https://aur.archlinux.org/packages.php?ID=3D14382
[2] https://aur.archlinux.org/packages.php?ID=3D55058
[3] https://aur.archlinux.org/packages.php?ID=3D14379
[4] https://aur.archlinux.org/packages.php?ID=3D55056

- speps -

--Signature=_Sat__17_Dec_2011_23_32_13_+0100_r_0jpZWYdIjX9Gde
Content-Type: application/pgp-signature

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.11 (GNU/Linux)

iQEcBAEBAgAGBQJO7RhtAAoJEM9wN6Tyf7faZOsIAKsC/o5IizNwY/CvQoJzW3u9
j+J2j8YvZ1kxI+d2x7e+cBCYizxQdTxi3WZaZylCEarIOXErchEh04TtFnUo3+38
FLWIIJB8bQMIxYOBxCtYV5zK7q4wUXavp/pbRXQ+U0SmHbxbq2c5xiG/U4JiJZ5R
nVglILDceP277I0UFzEUhvcDqpcCj4nCczCIP5jl0QYcUo3WTCoGL5ki74ekvLkB
GZZzQJ22WIH+Xj23TuVaZo9uGjVwVzTP2h2bx2JU83jeA2euo2BUrB8pIyt8jobO
nYlUQYF/pGscR91HGRSCbWtLZo5/OdAU56UeaBBiqoIdPbMO6rYnGEcRyH9/bIc=
=7tKK
-----END PGP SIGNATURE-----

--Signature=_Sat__17_Dec_2011_23_32_13_+0100_r_0jpZWYdIjX9Gde--

