Path: news.gmane.org!not-for-mail
From: Dieter Plaetinck <dieter-7FYLOmueu/EUehRvb1n7cg@public.gmane.org>
Newsgroups: gmane.linux.arch.releng
Subject: Re: Arch Linux Official Installation Guide in git
Date: Mon, 26 Dec 2011 17:21:37 +0100
Lines: 30
Approved: news@gmane.org
Message-ID: <20111226172137.22098ed6@plaetinck.be>
References: <CAO0v=MPT2VmKej3AQdNcqkGUzb_vAdSVaKt_kzH-8SNqJbxXZw@mail.gmail.com>
 <20111226170020.42c2d4d5@plaetinck.be>
 <CAO0v=MPU+RfMiPM1_Y8ZCVdWAGHDivRch=FFV1W3T4pZiZXDmA@mail.gmail.com>
Reply-To: Arch Linux Release Engineering <arch-releng-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>
NNTP-Posting-Host: lo.gmane.org
Mime-Version: 1.0
Content-Type: text/plain; charset=US-ASCII
Content-Transfer-Encoding: 7bit
X-Trace: dough.gmane.org 1324916560 31866 80.91.229.12 (26 Dec 2011 16:22:40 GMT)
X-Complaints-To: usenet@dough.gmane.org
NNTP-Posting-Date: Mon, 26 Dec 2011 16:22:40 +0000 (UTC)
To: Arch Linux Release Engineering <arch-releng-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>
Original-X-From: arch-releng-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org Mon Dec 26 17:22:36 2011
Return-path: <arch-releng-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>
Envelope-to: glar-arch-releng@m.gmane.org
Original-Received: from gerolde.archlinux.org ([66.211.214.132])
	by lo.gmane.org with esmtp (Exim 4.69)
	(envelope-from <arch-releng-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>)
	id 1RfDJr-0001d0-Vx
	for glar-arch-releng@m.gmane.org; Mon, 26 Dec 2011 17:22:36 +0100
Original-Received: from gudrun.archlinux.org (gudrun.archlinux.org [66.211.214.131])
	by gerolde.archlinux.org (Postfix) with ESMTP id 7A5CB9020A;
	Mon, 26 Dec 2011 11:22:32 -0500 (EST)
Original-Received: from gerolde.archlinux.org (gerolde.archlinux.org [66.211.214.132])
 by gudrun.archlinux.org (Postfix) with ESMTP id 012F486171
 for <arch-releng-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>; Mon, 26 Dec 2011 11:22:30 -0500 (EST)
Received-SPF: none (plaetinck.be: No applicable sender policy available)
 receiver=gerolde.archlinux.org; identity=mailfrom;
 envelope-from="dieter-7FYLOmueu/EUehRvb1n7cg@public.gmane.org"; helo=smtp.priorweb.be;
 client-ip=62.182.61.111
Original-Received: from smtp.priorweb.be (smtp01.priorweb.be [62.182.61.111])
 by gerolde.archlinux.org (Postfix) with ESMTPS id CFE3E90207
 for <arch-releng-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>; Mon, 26 Dec 2011 11:22:30 -0500 (EST)
Original-Received: from [178.79.146.162] (port=49589 helo=localhost.localdomain)
 by smtp.priorweb.be with esmtps (TLS1.0:DHE_RSA_AES_128_CBC_SHA1:16)
 (Exim 4.72) (envelope-from <dieter-7FYLOmueu/EUehRvb1n7cg@public.gmane.org>)
 id 1RfDJl-0007Ab-MP; Mon, 26 Dec 2011 17:22:29 +0100
In-Reply-To: <CAO0v=MPU+RfMiPM1_Y8ZCVdWAGHDivRch=FFV1W3T4pZiZXDmA-JsoAwUIsXosN+BqQ9rBEUg@public.gmane.org>
X-Mailer: Claws Mail 3.8.0 (GTK+ 2.24.8; x86_64-unknown-linux-gnu)
X-BeenThere: arch-releng-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org
X-Mailman-Version: 2.1.14
Precedence: list
List-Id: Arch Linux Release Engineering <arch-releng.archlinux.org>
List-Unsubscribe: <http://mailman.archlinux.org/mailman/options/arch-releng>, 
 <mailto:arch-releng-request-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org?subject=unsubscribe>
List-Archive: <http://mailman.archlinux.org/pipermail/arch-releng>
List-Post: <mailto:arch-releng-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>
List-Help: <mailto:arch-releng-request-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org?subject=help>
List-Subscribe: <http://mailman.archlinux.org/mailman/listinfo/arch-releng>,
 <mailto:arch-releng-request-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org?subject=subscribe>
Errors-To: arch-releng-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org
Original-Sender: arch-releng-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org
Xref: news.gmane.org gmane.linux.arch.releng:962
Archived-At: <http://permalink.gmane.org/gmane.linux.arch.releng/962>

On Mon, 26 Dec 2011 17:14:36 +0100
Karol Blazewicz <karol.blazewicz-Re5JQEeQqe8AvxtiuMwx3w@public.gmane.org> wrote:

> On Mon, Dec 26, 2011 at 5:00 PM, Dieter Plaetinck
> <dieter-7FYLOmueu/EUehRvb1n7cg@public.gmane.org> wrote:
> > On Mon, 26 Dec 2011 16:41:37 +0100
> > Karol Blazewicz <karol.blazewicz-Re5JQEeQqe8AvxtiuMwx3w@public.gmane.org> wrote:
> >
> >> Is
> >> http://projects.archlinux.org/aif.git/plain/doc/official_installation_guide_en
> >> the latest version? It says so on
> >> https://wiki.archlinux.org/index.php/Official_Installation_Guide.
> >> Will the Official Installation Guide that's in the wiki be updated?
> >
> > the "latest" is the one in the development branch.
> > the "latest official" is the one in the master branch.
> >
> > yes, I'll update it as soon as there's a new release version.
> >
> > Dieter
> 
> Where can I view the updated one?
> http://projects.archlinux.org/aif.git/tree/doc/official_installation_guide_en?h=develop
> is not it.

Right. currently you'll have to look at the upstream url (https://github.com/Dieterbe/aif) because
my config to push to the arch repos doesn't work right now. i'll fix that soon.

Dieter

