Path: news.gmane.org!not-for-mail
From: Dieter Plaetinck <dieter-7FYLOmueu/EUehRvb1n7cg@public.gmane.org>
Newsgroups: gmane.linux.arch.releng
Subject: Re: Christmas Release?
Date: Mon, 26 Dec 2011 14:41:08 +0100
Lines: 55
Approved: news@gmane.org
Message-ID: <20111226144108.509d18c5@plaetinck.be>
References: <4EE93AAC.5020604@archlinux.org> <4EE956D2.8040305@yahoo.com.ar>
 <20111215112630.3cec49ef@plaetinck.be>
 <4EE9DCAA.4090806@archlinux.org>
 <20111215124338.4c49da2c@plaetinck.be>
Reply-To: Arch Linux Release Engineering <arch-releng-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>
NNTP-Posting-Host: lo.gmane.org
Mime-Version: 1.0
Content-Type: multipart/signed; micalg=PGP-SHA1;
 boundary="Sig_/JKPXa6pxS9svpu4T=fWukcU"; protocol="application/pgp-signature"
X-Trace: dough.gmane.org 1324906942 7816 80.91.229.12 (26 Dec 2011 13:42:22 GMT)
X-Complaints-To: usenet@dough.gmane.org
NNTP-Posting-Date: Mon, 26 Dec 2011 13:42:22 +0000 (UTC)
To: Arch Linux Release Engineering <arch-releng-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>
Original-X-From: arch-releng-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org Mon Dec 26 14:42:18 2011
Return-path: <arch-releng-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>
Envelope-to: glar-arch-releng@m.gmane.org
Original-Received: from gerolde.archlinux.org ([66.211.214.132])
	by lo.gmane.org with esmtp (Exim 4.69)
	(envelope-from <arch-releng-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>)
	id 1RfAod-0002ch-3C
	for glar-arch-releng@m.gmane.org; Mon, 26 Dec 2011 14:42:11 +0100
Original-Received: from gudrun.archlinux.org (gudrun.archlinux.org [66.211.214.131])
	by gerolde.archlinux.org (Postfix) with ESMTP id 1FB46901F1;
	Mon, 26 Dec 2011 08:42:07 -0500 (EST)
Original-Received: from gerolde.archlinux.org (gerolde.archlinux.org [66.211.214.132])
 by gudrun.archlinux.org (Postfix) with ESMTP id 0B3C186170
 for <arch-releng-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>; Mon, 26 Dec 2011 08:42:06 -0500 (EST)
Received-SPF: none (plaetinck.be: No applicable sender policy available)
 receiver=gerolde.archlinux.org; identity=mailfrom;
 envelope-from="dieter-7FYLOmueu/EUehRvb1n7cg@public.gmane.org"; helo=smtp.priorweb.be;
 client-ip=62.182.61.111
Original-Received: from smtp.priorweb.be (smtp01.priorweb.be [62.182.61.111])
 by gerolde.archlinux.org (Postfix) with ESMTPS id D76C4901EC
 for <arch-releng-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>; Mon, 26 Dec 2011 08:42:05 -0500 (EST)
Original-Received: from [178.79.146.162] (port=47153 helo=localhost.localdomain)
 by smtp.priorweb.be with esmtps (TLS1.0:DHE_RSA_AES_128_CBC_SHA1:16)
 (Exim 4.72) (envelope-from <dieter-7FYLOmueu/EUehRvb1n7cg@public.gmane.org>) id 1RfAoW-0001Bg-SR
 for arch-releng-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org; Mon, 26 Dec 2011 14:42:04 +0100
In-Reply-To: <20111215124338.4c49da2c-7FYLOmueu/EUehRvb1n7cg@public.gmane.org>
X-Mailer: Claws Mail 3.8.0 (GTK+ 2.24.8; x86_64-unknown-linux-gnu)
X-BeenThere: arch-releng-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org
X-Mailman-Version: 2.1.14
Precedence: list
List-Id: Arch Linux Release Engineering <arch-releng.archlinux.org>
List-Unsubscribe: <http://mailman.archlinux.org/mailman/options/arch-releng>, 
 <mailto:arch-releng-request-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org?subject=unsubscribe>
List-Archive: <http://mailman.archlinux.org/pipermail/arch-releng>
List-Post: <mailto:arch-releng-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>
List-Help: <mailto:arch-releng-request-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org?subject=help>
List-Subscribe: <http://mailman.archlinux.org/mailman/listinfo/arch-releng>,
 <mailto:arch-releng-request-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org?subject=subscribe>
Errors-To: arch-releng-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org
Original-Sender: arch-releng-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org
Xref: news.gmane.org gmane.linux.arch.releng:958
Archived-At: <http://permalink.gmane.org/gmane.linux.arch.releng/958>

--Sig_/JKPXa6pxS9svpu4T=fWukcU
Content-Type: text/plain; charset=ISO-8859-1
Content-Transfer-Encoding: quoted-printable

On Thu, 15 Dec 2011 12:43:38 +0100
Dieter Plaetinck <dieter-7FYLOmueu/EUehRvb1n7cg@public.gmane.org> wrote:

> On Thu, 15 Dec 2011 12:40:26 +0100
> Thomas B=E4chler <thomas-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org> wrote:
>=20
> > Any regressions compared to the previous release?
>=20
> https://bugs.archlinux.org/task/26306
> https://bugs.archlinux.org/task/26717
>=20
> > Once pacman 4 goes to core, we need signing in archiso and AIF. The
> > archiso part is rather easy (set up a keyring for the live
> > environment), the AIF part is harder
>=20
> you think?
> we discussed this and it seemed pretty easy to me. see:
> https://bugs.archlinux.org/task/27583

well, the regressions should be fixed.
there are still a bunch of pending issues:
https://bugs.archlinux.org/index.php?do=3Dindex&project=3D6&status[]=3Dopen
at this point, you'll also see a bunch of blockdevices (/dev/dm* and /dev/l=
oop* devices) which shouldn't appear,
i'm still looking for a clean way to be able to filter those out. (maybe ju=
st match their name..)

but you can already start testing testbuilds from http://releng.archlinux.o=
rg/isos/
please report feedback @ http://www.archlinux.org/releng/feedback/

Dieter

--Sig_/JKPXa6pxS9svpu4T=fWukcU
Content-Type: application/pgp-signature; name=signature.asc
Content-Disposition: attachment; filename=signature.asc

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.11 (GNU/Linux)

iQEcBAEBAgAGBQJO+Hl0AAoJEPLbtJMZhamS1rsH/RQOlxGkMroYHbvr0k9K+Cd7
C9qkh4Si1rA5xUskrUcxmB5IJTWqOfy2X+LZOHGeeWqxHNXgltOY7FM3DOeRkEoC
Z1gkODlLhDs3aV9W4i9cR80kyvt7+6w0GOy0mIPR+PTINeUrM2jzcAjyFbD+eueq
GKt4y1zPQWv9/pT4LrqmJ8MA0+LaFjqntESCcXPNkoZXhQJCjxX3VOJ3NzJiGlvP
cnBQ3NDGM14goIOv2bct97LEUgq4ho6tb9A4HPN01f9a8vZufUzZEp/miMMY9y7h
Ezjyh4msJvQVmhLkH2rq7Hl0XN63f0oihlqES3R/uf9xhkrqlq8sTQnOY9QilO4=
=mL4j
-----END PGP SIGNATURE-----

--Sig_/JKPXa6pxS9svpu4T=fWukcU--

