Path: news.gmane.org!not-for-mail
From: Arch Website Notification <nobody-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>
Newsgroups: gmane.linux.arch.tur.user
Subject: Signoff report for [community-testing]
Date: Fri, 23 Dec 2011 09:07:04 -0000
Lines: 68
Approved: news@gmane.org
Message-ID: <20111223090704.6086.37206@gerolde.archlinux.org>
Reply-To: "Discussion about the Arch User Repository \(AUR\)"
 <aur-general-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>
NNTP-Posting-Host: lo.gmane.org
Mime-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: quoted-printable
X-Trace: dough.gmane.org 1324631233 31608 80.91.229.12 (23 Dec 2011 09:07:13 GMT)
X-Complaints-To: usenet@dough.gmane.org
NNTP-Posting-Date: Fri, 23 Dec 2011 09:07:13 +0000 (UTC)
To: aur-general-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org
Original-X-From: aur-general-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org Fri Dec 23 10:07:09 2011
Return-path: <aur-general-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>
Envelope-to: glatu-tur-users@m.gmane.org
Original-Received: from gerolde.archlinux.org ([66.211.214.132])
	by lo.gmane.org with esmtp (Exim 4.69)
	(envelope-from <aur-general-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>)
	id 1Re15o-0002ag-W8
	for glatu-tur-users@m.gmane.org; Fri, 23 Dec 2011 10:07:09 +0100
Original-Received: from gudrun.archlinux.org (gudrun.archlinux.org [66.211.214.131])
	by gerolde.archlinux.org (Postfix) with ESMTP id 772F99006D;
	Fri, 23 Dec 2011 04:07:05 -0500 (EST)
Original-Received: from gerolde.archlinux.org (gerolde.archlinux.org [66.211.214.132])
 by gudrun.archlinux.org (Postfix) with ESMTP id 6875686163
 for <aur-general-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>; Fri, 23 Dec 2011 04:07:04 -0500 (EST)
Original-Received: from gerolde.archlinux.org (gerolde.archlinux.org [127.0.0.1])
 by gerolde.archlinux.org (Postfix) with ESMTP id 481CB90069
 for <aur-general-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>; Fri, 23 Dec 2011 04:07:04 -0500 (EST)
X-BeenThere: aur-general-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org
X-Mailman-Version: 2.1.14
Precedence: list
List-Id: "Discussion about the Arch User Repository \(AUR\)"
 <aur-general.archlinux.org>
List-Unsubscribe: <http://mailman.archlinux.org/mailman/options/aur-general>, 
 <mailto:aur-general-request-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org?subject=unsubscribe>
List-Archive: <http://mailman.archlinux.org/pipermail/aur-general>
List-Post: <mailto:aur-general-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>
List-Help: <mailto:aur-general-request-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org?subject=help>
List-Subscribe: <http://mailman.archlinux.org/mailman/listinfo/aur-general>,
 <mailto:aur-general-request-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org?subject=subscribe>
Errors-To: aur-general-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org
Original-Sender: aur-general-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org
Xref: news.gmane.org gmane.linux.arch.tur.user:23163
Archived-At: <http://permalink.gmane.org/gmane.linux.arch.tur.user/23163>

=3D=3D=3D Signoff report for [community-testing] =3D=3D=3D
https://www.archlinux.org/packages/signoffs/

There are currently:
* 0 new packages in last 24 hours
* 0 known bad packages
* 0 packages not accepting signoffs
* 2 fully signed off packages
* 8 packages missing signoffs
* 8 packages older than 14 days

(Note: the word 'package' as used here refers to packages as grouped by
pkgbase, architecture, and repository; e.g., one PKGBUILD produces one
package per architecture, even if it is a split package.)



=3D=3D Incomplete signoffs for [community] (6 total) =3D=3D

* fail2ban-0.8.4-4 (any)
    1/2 signoffs
* expac-0.07-1 (i686)
    0/2 signoffs
* packagekit-0.6.19-3 (i686)
    0/2 signoffs
* vtk-5.8.0-7 (i686)
    0/2 signoffs
* packagekit-0.6.19-3 (x86_64)
    1/2 signoffs
* vtk-5.8.0-7 (x86_64)
    0/2 signoffs

=3D=3D Incomplete signoffs for [unknown] (2 total) =3D=3D

* percona-server-5.5.17_rel22.1-1 (i686)
    0/2 signoffs
* percona-server-5.5.17_rel22.1-1 (x86_64)
    1/2 signoffs


=3D=3D Completed signoffs (2 total) =3D=3D

* pacman-contrib-4.0.1-1 (any)
* expac-0.07-1 (x86_64)


=3D=3D All packages in [community-testing] for more than 14 days (8 total) =
=3D=3D

* expac-0.07-1 (i686), since 2011-10-13
* expac-0.07-1 (x86_64), since 2011-10-13
* pacman-contrib-4.0.1-1 (any), since 2011-11-25
* percona-server-5.5.17_rel22.1-1 (i686), since 2011-11-27
* percona-server-5.5.17_rel22.1-1 (x86_64), since 2011-11-27
* fail2ban-0.8.4-4 (any), since 2011-11-30
* packagekit-0.6.19-3 (i686), since 2011-11-30
* packagekit-0.6.19-3 (x86_64), since 2011-11-30


=3D=3D Top five in signoffs in last 24 hours =3D=3D

1. tomegun - 2 signoffs
2. ibiru - 2 signoffs
3. dan - 1 signoffs
4. bpiotrowski - 1 signoffs
5. foutrelis - 1 signoffs


