Path: news.gmane.org!not-for-mail
From: Arch Website Notification <nobody-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>
Newsgroups: gmane.linux.arch.devel
Subject: Signoff report for [testing]
Date: Fri, 23 Dec 2011 09:07:04 -0000
Lines: 116
Approved: news@gmane.org
Message-ID: <20111223090704.6081.88329@gerolde.archlinux.org>
Reply-To: Public mailing list for Arch Linux development
 <arch-dev-public-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>
NNTP-Posting-Host: lo.gmane.org
Mime-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: quoted-printable
X-Trace: dough.gmane.org 1324631238 31678 80.91.229.12 (23 Dec 2011 09:07:18 GMT)
X-Complaints-To: usenet@dough.gmane.org
NNTP-Posting-Date: Fri, 23 Dec 2011 09:07:18 +0000 (UTC)
To: arch-dev-public-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org
Original-X-From: arch-dev-public-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org Fri Dec 23 10:07:14 2011
Return-path: <arch-dev-public-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>
Envelope-to: glad-arch-dev-public@m.gmane.org
Original-Received: from gerolde.archlinux.org ([66.211.214.132])
	by lo.gmane.org with esmtp (Exim 4.69)
	(envelope-from <arch-dev-public-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>)
	id 1Re15t-0002ci-BR
	for glad-arch-dev-public@m.gmane.org; Fri, 23 Dec 2011 10:07:14 +0100
Original-Received: from gudrun.archlinux.org (gudrun.archlinux.org [66.211.214.131])
	by gerolde.archlinux.org (Postfix) with ESMTP id 6C8C990076;
	Fri, 23 Dec 2011 04:07:08 -0500 (EST)
Original-Received: from gerolde.archlinux.org (gerolde.archlinux.org [66.211.214.132])
 by gudrun.archlinux.org (Postfix) with ESMTP id 6B7B886164
 for <arch-dev-public-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>; Fri, 23 Dec 2011 04:07:04 -0500 (EST)
Original-Received: from gerolde.archlinux.org (gerolde.archlinux.org [127.0.0.1])
 by gerolde.archlinux.org (Postfix) with ESMTP id 53C329006D
 for <arch-dev-public-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>; Fri, 23 Dec 2011 04:07:04 -0500 (EST)
X-BeenThere: arch-dev-public-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org
X-Mailman-Version: 2.1.14
Precedence: list
List-Id: Public mailing list for Arch Linux development
 <arch-dev-public.archlinux.org>
List-Unsubscribe: <http://mailman.archlinux.org/mailman/options/arch-dev-public>, 
 <mailto:arch-dev-public-request-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org?subject=unsubscribe>
List-Archive: <http://mailman.archlinux.org/pipermail/arch-dev-public>
List-Post: <mailto:arch-dev-public-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>
List-Help: <mailto:arch-dev-public-request-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org?subject=help>
List-Subscribe: <http://mailman.archlinux.org/mailman/listinfo/arch-dev-public>, 
 <mailto:arch-dev-public-request-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org?subject=subscribe>
Errors-To: arch-dev-public-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org
Original-Sender: arch-dev-public-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org
Xref: news.gmane.org gmane.linux.arch.devel:16832
Archived-At: <http://permalink.gmane.org/gmane.linux.arch.devel/16832>

=3D=3D=3D Signoff report for [testing] =3D=3D=3D
https://www.archlinux.org/packages/signoffs/

There are currently:
* 2 new packages in last 24 hours
* 0 known bad packages
* 0 packages not accepting signoffs
* 11 fully signed off packages
* 18 packages missing signoffs
* 23 packages older than 14 days

(Note: the word 'package' as used here refers to packages as grouped by
pkgbase, architecture, and repository; e.g., one PKGBUILD produces one
package per architecture, even if it is a split package.)


=3D=3D New packages in [testing] in last 24 hours (2 total) =3D=3D

* linux-3.1.6-1 (i686)
* linux-3.1.6-1 (x86_64)


=3D=3D Incomplete signoffs for [core] (3 total) =3D=3D

* linux-3.1.6-1 (i686)
    1/2 signoffs
* nilfs-utils-2.1.0-2 (i686)
    0/2 signoffs
* nilfs-utils-2.1.0-2 (x86_64)
    1/2 signoffs

=3D=3D Incomplete signoffs for [extra] (15 total) =3D=3D

* texlive-bibtexextra-2011.24688-1 (any)
    1/2 signoffs
* texlive-games-2011.24714-1 (any)
    0/2 signoffs
* texlive-genericextra-2011.24609-1 (any)
    0/2 signoffs
* texlive-htmlxml-2011.24013-1 (any)
    0/2 signoffs
* texlive-humanities-2011.24631-1 (any)
    0/2 signoffs
* texlive-langcjk-2011.24689-1 (any)
    0/2 signoffs
* texlive-langcyrillic-2011.24029-1 (any)
    0/2 signoffs
* texlive-langextra-2011.23959-1 (any)
    0/2 signoffs
* texlive-langgreek-2011.24147-1 (any)
    0/2 signoffs
* texlive-music-2011.24518-1 (any)
    0/2 signoffs
* texlive-pictures-2011.24715-1 (any)
    1/2 signoffs
* texlive-plainextra-2011.23567-1 (any)
    0/2 signoffs
* texlive-pstricks-2011.24695-1 (any)
    0/2 signoffs
* texlive-publishers-2011.24723-1 (any)
    0/2 signoffs
* texlive-bin-2011.3-1 (i686)
    0/2 signoffs


=3D=3D Completed signoffs (11 total) =3D=3D

* pacman-4.0.1-1 (i686)
* linux-3.1.6-1 (x86_64)
* pacman-4.0.1-1 (x86_64)
* namcap-3.2.1-1 (any)
* texlive-core-2011.24722-1 (any)
* texlive-fontsextra-2011.24706-1 (any)
* texlive-latexextra-2011.24718-1 (any)
* texlive-science-2011.24724-1 (any)
* pyalpm-0.5.3-1 (i686)
* pyalpm-0.5.3-1 (x86_64)
* texlive-bin-2011.3-1 (x86_64)


=3D=3D All packages in [testing] for more than 14 days (23 total) =3D=3D

* pyalpm-0.5.3-1 (i686), since 2011-10-15
* pyalpm-0.5.3-1 (x86_64), since 2011-10-15
* namcap-3.2.1-1 (any), since 2011-10-20
* pacman-4.0.1-1 (i686), since 2011-11-21
* pacman-4.0.1-1 (x86_64), since 2011-11-21
* texlive-pictures-2011.24715-1 (any), since 2011-12-04
* texlive-fontsextra-2011.24706-1 (any), since 2011-12-04
* texlive-music-2011.24518-1 (any), since 2011-12-04
* texlive-publishers-2011.24723-1 (any), since 2011-12-04
* texlive-humanities-2011.24631-1 (any), since 2011-12-04
* texlive-langgreek-2011.24147-1 (any), since 2011-12-04
* texlive-langcyrillic-2011.24029-1 (any), since 2011-12-04
* texlive-pstricks-2011.24695-1 (any), since 2011-12-04
* texlive-htmlxml-2011.24013-1 (any), since 2011-12-04
* texlive-langcjk-2011.24689-1 (any), since 2011-12-04
* texlive-bibtexextra-2011.24688-1 (any), since 2011-12-04
* texlive-core-2011.24722-1 (any), since 2011-12-04
* texlive-plainextra-2011.23567-1 (any), since 2011-12-04
* texlive-science-2011.24724-1 (any), since 2011-12-04
* texlive-games-2011.24714-1 (any), since 2011-12-04
* texlive-genericextra-2011.24609-1 (any), since 2011-12-04
* texlive-latexextra-2011.24718-1 (any), since 2011-12-04
* texlive-langextra-2011.23959-1 (any), since 2011-12-04


=3D=3D Top five in signoffs in last 24 hours =3D=3D

1. tomegun - 2 signoffs
2. ibiru - 2 signoffs
3. dan - 1 signoffs
4. bpiotrowski - 1 signoffs
5. foutrelis - 1 signoffs


