Path: news.gmane.org!not-for-mail
From: =?utf-8?q?Arch_Linux=3A_Recent_news_updates=3A_Ionu=C8=9B_Mircea_B=C3=AEr?=
 =?utf-8?q?u?= <announce-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>
Newsgroups: gmane.linux.arch.announce
Subject: wiki and bbs downtime
Date: Mon, 24 Oct 2011 20:01:10 -0000
Lines: 14
Approved: news@gmane.org
Message-ID: <36049.5871319019$1319486503@news.gmane.org>
Reply-To: Arch Linux Announcements <arch-announce-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>
NNTP-Posting-Host: lo.gmane.org
Mime-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: base64
X-Trace: dough.gmane.org 1319486503 19685 80.91.229.12 (24 Oct 2011 20:01:43 GMT)
X-Complaints-To: usenet@dough.gmane.org
NNTP-Posting-Date: Mon, 24 Oct 2011 20:01:43 +0000 (UTC)
To: arch-announce-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org
Original-X-From: arch-announce-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org Mon Oct 24 22:01:40 2011
Return-path: <arch-announce-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>
Envelope-to: glaa-arch-announce@m.gmane.org
Original-Received: from gerolde.archlinux.org ([66.211.214.132] helo=archlinux.org)
	by lo.gmane.org with esmtp (Exim 4.69)
	(envelope-from <arch-announce-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>)
	id 1RIQiJ-0004Fu-Bm
	for glaa-arch-announce@m.gmane.org; Mon, 24 Oct 2011 22:01:39 +0200
Original-Received: from gudrun.archlinux.org (gudrun.archlinux.org [66.211.214.131])
	by archlinux.org (Postfix) with ESMTP id 757C49007D;
	Mon, 24 Oct 2011 16:01:13 -0400 (EDT)
Original-Received: from gerolde.archlinux.org (gerolde.archlinux.org [66.211.214.132])
 by gudrun.archlinux.org (Postfix) with ESMTP id 2774384A57
 for <arch-announce-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>; Mon, 24 Oct 2011 16:01:11 -0400 (EDT)
User-Agent: rss2email
X-BeenThere: arch-announce-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org
X-Mailman-Version: 2.1.14
Precedence: list
List-Id: Arch Linux Announcements <arch-announce.archlinux.org>
List-Unsubscribe: <http://mailman.archlinux.org/mailman/options/arch-announce>, 
 <mailto:arch-announce-request-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org?subject=unsubscribe>
List-Archive: <http://mailman.archlinux.org/pipermail/arch-announce>
List-Post: <mailto:arch-announce-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>
List-Help: <mailto:arch-announce-request-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org?subject=help>
List-Subscribe: <http://mailman.archlinux.org/mailman/listinfo/arch-announce>, 
 <mailto:arch-announce-request-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org?subject=subscribe>
Errors-To: arch-announce-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org
Original-Sender: arch-announce-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org
Xref: news.gmane.org gmane.linux.arch.announce:256
Archived-At: <http://permalink.gmane.org/gmane.linux.arch.announce/256>

SW9udcibIE1pcmNlYSBCw65ydSB3cm90ZToKCk9uIE9jdG9iZXIgMjN0aCB0aGUgZGF0YSBjZW50
ZXIgd2hlcmUgb3VyIHNlcnZlciBpcyBsb2NhdGVkIGhhZCBhIHBvd2VyIGZhaWx1cmUuClRoZSBz
ZXJ2ZXIgd2FzIHJlYm9vdGVkIGFuZCBhdCB0aGUgZmlyc3QgbG9vayBldmVyeXRoaW5nIHdhcyBm
aW5lLgoKSW4gdGhlIG1vcm5pbmcgd2Ugbm90aWNlZCB0aGF0IHRoZSBwZXJmb3JtYW5jZSB3YXMg
YmFkIGFuZCBzdGFydGVkIHRvCmludmVzdGlnYXRlIGFuZCBmb3VuZCBvdXQgdGhhdCBvbmUgb2Yg
dGhlIGhhcmQgZGlza3Mgd2FzIGZhaWxpbmcuCgpUaGUgZHJpdmUgaGFzIGJlZW4gcmVwbGFjZWQg
YW5kIGlzIG5vdyBzeW5jaHJvbml6aW5nLgoKV2UgYXJlIHNvcnJ5IGZvciB0aGUgbG9uZyBkb3du
dGltZSBhbmQgd2UgaGF2ZSBhZGp1c3RlZCBvdXIgcHJvY2VkdXJlcyBzbyB0aGF0CnRoaXMgd29u
J3QgaGFwcGVuIGFnYWluLgoKVVJMOiBodHRwOi8vd3d3LmFyY2hsaW51eC5vcmcvbmV3cy93aWtp
LWFuZC1iYnMtZG93bnRpbWUvCl9fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19fX19f
X19fX19fX19fCmFyY2gtYW5ub3VuY2UgbWFpbGluZyBsaXN0CmFyY2gtYW5ub3VuY2VAYXJjaGxp
bnV4Lm9yZwpodHRwOi8vbWFpbG1hbi5hcmNobGludXgub3JnL21haWxtYW4vbGlzdGluZm8vYXJj
aC1hbm5vdW5jZQo=

