Path: news.gmane.org!not-for-mail
From: Greg Larkin <glarkin-4nlIFiKd+71dpuOT5p4XHl6hYfS7NtTn@public.gmane.org>
Newsgroups: gmane.comp.sysutils.backup.tarsnap.user
Subject: How to remove an unused machine?
Date: Thu, 15 Dec 2011 11:15:51 -0500
Lines: 18
Approved: news@gmane.org
Message-ID: <4EEA1D37.6000908@sourcehosting.net>
NNTP-Posting-Host: lo.gmane.org
Mime-Version: 1.0
Content-Type: text/plain; charset=ISO-8859-1
Content-Transfer-Encoding: 7bit
X-Trace: dough.gmane.org 1323965782 9787 80.91.229.12 (15 Dec 2011 16:16:22 GMT)
X-Complaints-To: usenet@dough.gmane.org
NNTP-Posting-Date: Thu, 15 Dec 2011 16:16:22 +0000 (UTC)
To: tarsnap-users-C5KLY5ri3yZBDgjK7y7TUQ@public.gmane.org
Original-X-From: tarsnap-users-return-472-gcsbtu-tarsnap-users=m.gmane.org-C5KLY5ri3yZBDgjK7y7TUQ@public.gmane.org Thu Dec 15 17:16:14 2011
Return-path: <tarsnap-users-return-472-gcsbtu-tarsnap-users=m.gmane.org-C5KLY5ri3yZBDgjK7y7TUQ@public.gmane.org>
Envelope-to: gcsbtu-tarsnap-users-1dZseelyfdZg9hUCZPvPmw@public.gmane.org
Original-Received: from mx2.tarsnap.com ([208.79.82.75])
	by lo.gmane.org with smtp (Exim 4.69)
	(envelope-from <tarsnap-users-return-472-gcsbtu-tarsnap-users=m.gmane.org-C5KLY5ri3yZBDgjK7y7TUQ@public.gmane.org>)
	id 1RbDyf-0001AT-QQ
	for gcsbtu-tarsnap-users-1dZseelyfdZg9hUCZPvPmw@public.gmane.org; Thu, 15 Dec 2011 17:16:14 +0100
Original-Received: (qmail 12011 invoked from network); 15 Dec 2011 16:16:05 -0000
Original-Received: from unknown (HELO mx1.tarsnap.com) (192.168.0.25)
  by mx2.tarsnap.com with SMTP; 15 Dec 2011 16:16:05 -0000
Original-Received: (qmail 11819 invoked by uid 1025); 15 Dec 2011 16:16:02 -0000
Mailing-List: contact tarsnap-users-help-C5KLY5ri3yZBDgjK7y7TUQ@public.gmane.org; run by ezmlm
Precedence: bulk
List-Post: <mailto:tarsnap-users-C5KLY5ri3yZBDgjK7y7TUQ@public.gmane.org>
List-Help: <mailto:tarsnap-users-help-C5KLY5ri3yZBDgjK7y7TUQ@public.gmane.org>
List-Unsubscribe: <mailto:tarsnap-users-unsubscribe-C5KLY5ri3yZBDgjK7y7TUQ@public.gmane.org>
List-Subscribe: <mailto:tarsnap-users-subscribe-C5KLY5ri3yZBDgjK7y7TUQ@public.gmane.org>
Delivered-To: mailing list tarsnap-users-C5KLY5ri3yZBDgjK7y7TUQ@public.gmane.org
Original-Received: (qmail 11812 invoked from network); 15 Dec 2011 16:16:02 -0000
User-Agent: Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.6; en-US; rv:1.9.2.24) Gecko/20111103 Lightning/1.0b2 Thunderbird/3.1.16
X-SA-Exim-Connect-IP: 68.189.245.235
X-SA-Exim-Mail-From: glarkin-4nlIFiKd+71dpuOT5p4XHl6hYfS7NtTn@public.gmane.org
X-Spam-Checker-Version: SpamAssassin 3.3.1 (2010-03-16) on
	mail1.sourcehosting.net
X-Spam-Level: 
X-Spam-Status: No, score=0.4 required=5.0 tests=AWL,BAYES_00,RCVD_IN_RP_RNBL,
	RCVD_IN_SORBS_DUL,RDNS_DYNAMIC,TVD_RCVD_IP autolearn=no version=3.3.1
X-SA-Exim-Version: 4.2
X-SA-Exim-Scanned: Yes (on mail1.sourcehosting.net)
Xref: news.gmane.org gmane.comp.sysutils.backup.tarsnap.user:452
Archived-At: <http://permalink.gmane.org/gmane.comp.sysutils.backup.tarsnap.user/452>

Hi,

I've been using tarsnap for a few weeks now, and it's working well. 
During my initial POC tests, I managed to generate two keys for the same
machine.  Now I have the same hostname listed twice in the web UI, but
only one is active. 

Is there a way to delete the unused machine and its keys from the
backend?  I don't see that option, but I may be missing something very
obvious.

Thank you,
Greg Larkin


	<http://www.linkedin.com/e/sig/146767/>


