Path: news.gmane.org!not-for-mail
From: =?UTF-8?B?QmFydMWCb21pZWogUGlvdHJvd3NraQ==?= <barthalion-Re5JQEeQqe8AvxtiuMwx3w@public.gmane.org>
Newsgroups: gmane.linux.arch.tur.user
Subject: Re: Merge request emacs-rtf-mode
Date: Sun, 18 Dec 2011 07:45:26 +0100
Lines: 47
Approved: news@gmane.org
Message-ID: <4EED8C06.8030407@gmail.com>
References: <4EED0A3D.6030400@t-online.de>
Reply-To: "Discussion about the Arch User Repository \(AUR\)"
 <aur-general-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>
NNTP-Posting-Host: lo.gmane.org
Mime-Version: 1.0
Content-Type: multipart/signed; micalg=pgp-sha1;
 protocol="application/pgp-signature";
 boundary="------------enig464C36FF1CE154F2AEF54B0C"
X-Trace: dough.gmane.org 1324190745 5486 80.91.229.12 (18 Dec 2011 06:45:45 GMT)
X-Complaints-To: usenet@dough.gmane.org
NNTP-Posting-Date: Sun, 18 Dec 2011 06:45:45 +0000 (UTC)
To: "Discussion about the Arch User Repository (AUR)"
 <aur-general-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>
Original-X-From: aur-general-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org Sun Dec 18 07:45:41 2011
Return-path: <aur-general-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>
Envelope-to: glatu-tur-users@m.gmane.org
Original-Received: from gerolde.archlinux.org ([66.211.214.132])
	by lo.gmane.org with esmtp (Exim 4.69)
	(envelope-from <aur-general-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>)
	id 1RcAV9-0002r7-P2
	for glatu-tur-users@m.gmane.org; Sun, 18 Dec 2011 07:45:40 +0100
Original-Received: from gudrun.archlinux.org (gudrun.archlinux.org [66.211.214.131])
	by gerolde.archlinux.org (Postfix) with ESMTP id 60F4790027;
	Sun, 18 Dec 2011 01:45:36 -0500 (EST)
Original-Received: from gerolde.archlinux.org (gerolde.archlinux.org [66.211.214.132])
 by gudrun.archlinux.org (Postfix) with ESMTP id 59BA38615D
 for <aur-general-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>; Sun, 18 Dec 2011 01:45:34 -0500 (EST)
Received-SPF: pass (gmail.com ... _spf.google.com: 74.125.83.44 is authorized
 to use 'barthalion-Re5JQEeQqe8AvxtiuMwx3w@public.gmane.org' in 'mfrom' identity (mechanism
 'ip4:74.125.0.0/16' matched)) receiver=gerolde.archlinux.org;
 identity=mailfrom; envelope-from="barthalion-Re5JQEeQqe8AvxtiuMwx3w@public.gmane.org";
 helo=mail-ee0-f44.google.com; client-ip=74.125.83.44
Original-Received: from mail-ee0-f44.google.com (mail-ee0-f44.google.com [74.125.83.44])
 by gerolde.archlinux.org (Postfix) with ESMTPS id 12E4790026
 for <aur-general-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>; Sun, 18 Dec 2011 01:45:33 -0500 (EST)
Original-Received: by eekc14 with SMTP id c14so3385671eek.3
 for <aur-general-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>; Sat, 17 Dec 2011 22:45:32 -0800 (PST)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=gmail.com; s=gamma;
 h=message-id:date:from:user-agent:mime-version:to:subject:references
 :in-reply-to:x-enigmail-version:content-type;
 bh=MoNlDsAgRPCWxEirbs+PnqjyspDmZtqtyxmf34iNhvs=;
 b=AtI5iCFq0R1v1LPGa7J3mMczixfzaCt88sxIFGFk7PKI68am1HShBUlEma+mMaFclu
 ozptE8j4nL/RLnSgFoLLzBHIQOzZ5Be4yMBfcWH+fRNzuFwbqC+e+CUGIWpRgVroCm5p
 joK9Ht7xi8kpIbqZZVdL0/JO5MqZfakhxySlk=
Original-Received: by 10.14.124.144 with SMTP id x16mr2211599eeh.110.1324190732039;
 Sat, 17 Dec 2011 22:45:32 -0800 (PST)
Original-Received: from [192.168.0.11] ([79.175.253.235])
 by mx.google.com with ESMTPS id x12sm25640104eef.9.2011.12.17.22.45.30
 (version=SSLv3 cipher=OTHER); Sat, 17 Dec 2011 22:45:30 -0800 (PST)
User-Agent: Mozilla/5.0 (X11; Linux x86_64;
 rv:8.0) Gecko/20111108 Thunderbird/8.0
In-Reply-To: <4EED0A3D.6030400-zqRNUXuvxA0b1SvskN2V4Q@public.gmane.org>
X-Enigmail-Version: 1.3.4
X-BeenThere: aur-general-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org
X-Mailman-Version: 2.1.14
Precedence: list
List-Id: "Discussion about the Arch User Repository \(AUR\)"
 <aur-general.archlinux.org>
List-Unsubscribe: <http://mailman.archlinux.org/mailman/options/aur-general>, 
 <mailto:aur-general-request-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org?subject=unsubscribe>
List-Archive: <http://mailman.archlinux.org/pipermail/aur-general>
List-Post: <mailto:aur-general-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>
List-Help: <mailto:aur-general-request-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org?subject=help>
List-Subscribe: <http://mailman.archlinux.org/mailman/listinfo/aur-general>,
 <mailto:aur-general-request-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org?subject=subscribe>
Errors-To: aur-general-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org
Original-Sender: aur-general-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org
Xref: news.gmane.org gmane.linux.arch.tur.user:23075
Archived-At: <http://permalink.gmane.org/gmane.linux.arch.tur.user/23075>

This is an OpenPGP/MIME signed message (RFC 2440 and 3156)
--------------enig464C36FF1CE154F2AEF54B0C
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

On 17.12.2011 22:31, Stefan Husmann wrote:
> Hello,
>=20
> please merge emacs-rtf
>=20
> https://aur.archlinux.org/packages.php?ID=3D49924
>=20
> into the more accurately named alternative
>=20
> https://aur.archlinux.org/packages.php?ID=3D55061
>=20
> Thank you in advance.
>=20
> Regards Stefan

Done, thank you.

--=20
Bart=C5=82omiej Piotrowski
Arch Linux Trusted User
http://archlinux.org/


--------------enig464C36FF1CE154F2AEF54B0C
Content-Type: application/pgp-signature; name="signature.asc"
Content-Description: OpenPGP digital signature
Content-Disposition: attachment; filename="signature.asc"

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.11 (GNU/Linux)

iQEcBAEBAgAGBQJO7YwLAAoJELvkN3FIcyipKXwH/jCn7ef8Epsz6HGCMsIi7uoG
5decxWQP3ziOYZk1yrxx6n9uWjhhoK8bfNdaCO7+fOJYuShNe5tBbHKJgR5T8cyr
hSbYx5uN2J52v2Bn/mcMNeU5DbqfgCUp+OTc31PFPtWbh0l2h52FkQttNfiS4fjL
yyspG6xbPK/fbcUSEJjARXeRl3aQNAF8AH8MtWnZrEnT2nFSY15/TVj0Y0sJtYWy
suBdAPVJ1f607GWMVohSx0+gUDSDOYhGKXENRhRufj6jvypRArON94cykvDB8mwq
oqcjvUoFZFzRLW4DvfQ6lgdSqo/Fu0aNYv6tspd9mhneLEPmyxdHXU7lZ2Rktbo=
=b62+
-----END PGP SIGNATURE-----

--------------enig464C36FF1CE154F2AEF54B0C--

