Path: news.gmane.org!not-for-mail
From: Ionut Biru <ibiru@archlinux.org>
Newsgroups: gmane.linux.arch.general
Subject: Re: Is there a clean solution to get completely rid
 of Pulseaudio?
Date: Fri, 23 Dec 2011 11:17:41 +0200
Lines: 45
Approved: news@gmane.org
Message-ID: <4EF44735.8050009@archlinux.org>
References: <1324629697.9930.38.camel@localhost.localdomain>
Reply-To: General Discussion about Arch Linux <arch-general@archlinux.org>
NNTP-Posting-Host: lo.gmane.org
Mime-Version: 1.0
Content-Type: multipart/signed; micalg=pgp-sha1;
 protocol="application/pgp-signature";
 boundary="------------enig8F5C059CD20DC30D0A44C0F7"
X-Trace: dough.gmane.org 1324631884 3381 80.91.229.12 (23 Dec 2011 09:18:04 GMT)
X-Complaints-To: usenet@dough.gmane.org
NNTP-Posting-Date: Fri, 23 Dec 2011 09:18:04 +0000 (UTC)
To: General Discussion about Arch Linux <arch-general@archlinux.org>
Original-X-From: arch-general-bounces@archlinux.org Fri Dec 23 10:18:01 2011
Return-path: <arch-general-bounces@archlinux.org>
Envelope-to: glag-arch@m.gmane.org
Original-Received: from gerolde.archlinux.org ([66.211.214.132])
	by lo.gmane.org with esmtp (Exim 4.69)
	(envelope-from <arch-general-bounces@archlinux.org>)
	id 1Re1GI-0007dh-Uw
	for glag-arch@m.gmane.org; Fri, 23 Dec 2011 10:17:59 +0100
Original-Received: from gudrun.archlinux.org (gudrun.archlinux.org [66.211.214.131])
	by gerolde.archlinux.org (Postfix) with ESMTP id AE3CF9006B;
	Fri, 23 Dec 2011 04:17:54 -0500 (EST)
Original-Received: from gerolde.archlinux.org (gerolde.archlinux.org [66.211.214.132])
 by gudrun.archlinux.org (Postfix) with ESMTP id BE92D86163
 for <arch-general@archlinux.org>; Fri, 23 Dec 2011 04:17:52 -0500 (EST)
Original-Received: from [192.168.1.2] (unknown [81.196.77.121])
 by gerolde.archlinux.org (Postfix) with ESMTPSA id 81D2D90068
 for <arch-general@archlinux.org>; Fri, 23 Dec 2011 04:17:52 -0500 (EST)
User-Agent: Mozilla/5.0 (X11; Linux i686;
 rv:9.0) Gecko/20111221 Thunderbird/9.0
In-Reply-To: <1324629697.9930.38.camel@localhost.localdomain>
X-Enigmail-Version: 1.3.4
X-BeenThere: arch-general@archlinux.org
X-Mailman-Version: 2.1.14
Precedence: list
List-Id: General Discussion about Arch Linux <arch-general.archlinux.org>
List-Unsubscribe: <http://mailman.archlinux.org/mailman/options/arch-general>, 
 <mailto:arch-general-request@archlinux.org?subject=unsubscribe>
List-Archive: <http://mailman.archlinux.org/pipermail/arch-general>
List-Post: <mailto:arch-general@archlinux.org>
List-Help: <mailto:arch-general-request@archlinux.org?subject=help>
List-Subscribe: <http://mailman.archlinux.org/mailman/listinfo/arch-general>, 
 <mailto:arch-general-request@archlinux.org?subject=subscribe>
Errors-To: arch-general-bounces@archlinux.org
Original-Sender: arch-general-bounces@archlinux.org
Xref: news.gmane.org gmane.linux.arch.general:38356
Archived-At: <http://permalink.gmane.org/gmane.linux.arch.general/38356>

This is an OpenPGP/MIME signed message (RFC 2440 and 3156)
--------------enig8F5C059CD20DC30D0A44C0F7
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

On 12/23/2011 10:41 AM, Ralf Madorf wrote:
> Hi :)
>=20
> people told me that Arch Linux will not force me to install PA. Today I=

> continued to set up my Arch Linux. A cold still hinder me to work very
> long on my computer, so until now Google didn't help me to find an easy=

> solution to get rid of PA. Arch Linux on my machine does force me to
> install PA to keep the system consistent.
>=20

can you clarify that you are talking about pulseaudio and not about
libpulse?


--=20
Ionu=C8=9B


--------------enig8F5C059CD20DC30D0A44C0F7
Content-Type: application/pgp-signature; name="signature.asc"
Content-Description: OpenPGP digital signature
Content-Disposition: attachment; filename="signature.asc"

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.11 (GNU/Linux)
Comment: Using GnuPG with Mozilla - http://enigmail.mozdev.org/

iQEcBAEBAgAGBQJO9EdAAAoJEOjxi6FhUTe8rqEIAKecVBXp6eXF/5TmnYX+p3zu
J5FksNlcB+LYhfGbg+FyLI1YUEImm/kkCJu+luQfeZWSi0kuXPcB+WCYkcjojH71
DvJ53aKwG2Ltne8GxBZCeynUoiKyA3o918np25FgnzviYFojOR8eaRIiSapNNUXk
Ig526pK5muTd1yV3serWtAFJCfyg4qfkKQG9vdPn+zZjEnheAEv+Q2kxlSa76H3+
98fUP5JeZDbei7+pb7DEadL8naQSosYqzLIJt31EKAQwN7RBhSvjfAKQbQbsuYT5
TXNSvdHA9+xV478AhQkXYljJtAkDUglchCcYu3KL9Kxuu29Vd5Pkjj0uCdjsBc4=
=Ac0t
-----END PGP SIGNATURE-----

--------------enig8F5C059CD20DC30D0A44C0F7--

