Path: news.gmane.org!not-for-mail
From: David Kolb <david.kolb@krinchan.com>
Newsgroups: gmane.linux.arch.general
Subject: Re: Is there a clean solution to get completely rid
 of Pulseaudio?
Date: Thu, 29 Dec 2011 14:31:55 -0500
Lines: 35
Approved: news@gmane.org
Message-ID: <4EFCC02B.1020209@krinchan.com>
References: <1324629697.9930.38.camel@localhost.localdomain>
 <1324637340.10606.124.camel@localhost.localdomain>
 <CAMw+j7Lt_scVbwj7BfW6uQVfM6=a5R01vaGsLsvyGhZ0SiH1nA@mail.gmail.com>
 <10860676.TolBvm7Dii@leto> <20111229053635.GA2806@linlap.wavecable.com>
 <CAGQ70ev-Ek66X9ygkDfcD_N8XD++bO4NfjR1fenYOGk4ioDmNg@mail.gmail.com>
 <4EFCB80A.10000@gmail.com>
Reply-To: General Discussion about Arch Linux <arch-general@archlinux.org>
NNTP-Posting-Host: lo.gmane.org
Mime-Version: 1.0
Content-Type: text/plain; charset=ISO-8859-1
Content-Transfer-Encoding: 7bit
X-Trace: dough.gmane.org 1325187134 8105 80.91.229.12 (29 Dec 2011 19:32:14 GMT)
X-Complaints-To: usenet@dough.gmane.org
NNTP-Posting-Date: Thu, 29 Dec 2011 19:32:14 +0000 (UTC)
To: General Discussion about Arch Linux <arch-general@archlinux.org>
Original-X-From: arch-general-bounces@archlinux.org Thu Dec 29 20:32:10 2011
Return-path: <arch-general-bounces@archlinux.org>
Envelope-to: glag-arch@m.gmane.org
Original-Received: from gerolde.archlinux.org ([66.211.214.132])
	by lo.gmane.org with esmtp (Exim 4.69)
	(envelope-from <arch-general-bounces@archlinux.org>)
	id 1RgLhr-0007iJ-9u
	for glag-arch@m.gmane.org; Thu, 29 Dec 2011 20:32:03 +0100
Original-Received: from gudrun.archlinux.org (gudrun.archlinux.org [66.211.214.131])
	by gerolde.archlinux.org (Postfix) with ESMTP id 3462A90131;
	Thu, 29 Dec 2011 14:31:57 -0500 (EST)
Original-Received: from gerolde.archlinux.org (gerolde.archlinux.org [66.211.214.132])
 by gudrun.archlinux.org (Postfix) with ESMTP id 6555086179
 for <arch-general@archlinux.org>; Thu, 29 Dec 2011 14:31:55 -0500 (EST)
Received-SPF: none (krinchan.com: No applicable sender policy available)
 receiver=gerolde.archlinux.org; identity=mailfrom;
 envelope-from="david.kolb@krinchan.com"; helo=mail-yw0-f44.google.com;
 client-ip=209.85.213.44
Original-Received: from mail-yw0-f44.google.com (mail-yw0-f44.google.com
 [209.85.213.44])
 by gerolde.archlinux.org (Postfix) with ESMTPS id 3FF6B9012D
 for <arch-general@archlinux.org>; Thu, 29 Dec 2011 14:31:54 -0500 (EST)
Original-Received: by yhjj72 with SMTP id j72so7666961yhj.3
 for <arch-general@archlinux.org>; Thu, 29 Dec 2011 11:31:57 -0800 (PST)
Original-Received: by 10.236.168.40 with SMTP id j28mr16648324yhl.12.1325187117602;
 Thu, 29 Dec 2011 11:31:57 -0800 (PST)
Original-Received: from [10.63.65.152] (gw1.cox.com. [24.248.74.254])
 by mx.google.com with ESMTPS id i32sm86437411anm.6.2011.12.29.11.31.55
 (version=SSLv3 cipher=OTHER); Thu, 29 Dec 2011 11:31:56 -0800 (PST)
User-Agent: Mozilla/5.0 (Windows NT 5.1; rv:8.0) Gecko/20111105 Thunderbird/8.0
In-Reply-To: <4EFCB80A.10000@gmail.com>
X-Enigmail-Version: 1.3.4
X-BeenThere: arch-general@archlinux.org
X-Mailman-Version: 2.1.14
Precedence: list
List-Id: General Discussion about Arch Linux <arch-general.archlinux.org>
List-Unsubscribe: <http://mailman.archlinux.org/mailman/options/arch-general>, 
 <mailto:arch-general-request@archlinux.org?subject=unsubscribe>
List-Archive: <http://mailman.archlinux.org/pipermail/arch-general>
List-Post: <mailto:arch-general@archlinux.org>
List-Help: <mailto:arch-general-request@archlinux.org?subject=help>
List-Subscribe: <http://mailman.archlinux.org/mailman/listinfo/arch-general>, 
 <mailto:arch-general-request@archlinux.org?subject=subscribe>
Errors-To: arch-general-bounces@archlinux.org
Original-Sender: arch-general-bounces@archlinux.org
Xref: news.gmane.org gmane.linux.arch.general:38468
Archived-At: <http://permalink.gmane.org/gmane.linux.arch.general/38468>

-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

On 12/29/2011 1:57 PM, Don Juan wrote:
> If its a repeated question why not either no one respond which
> would force the person to research on their own or just send one
> message to check the wiki and or other pertinent place where the
> info has been said numerous times. I am on gumstix board as well
> and thats how they roll, stupid question or one thats commonly 
> asked and answered tons of times just get ignored or someone takes
> 2 seconds to say hey read the wiki or search the archives of this
> board question has been answered.
> 
> Just my .02 from a recent Arch convert.

I was wondering why the same thing didn't happen here.  The last time
I asked a silly question on a mailing list, I woke up the next morning
to over 200 messages to me, not the mailing list, with various links
to LMGTFY.com.  The lesson was learned without too much embarrassment
on my part and barely a blip of mailing list traffic.

- --David Kolb
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.9 (MingW32)
Comment: Using GnuPG with Mozilla - http://enigmail.mozdev.org/

iQEcBAEBAgAGBQJO/MAqAAoJEPmaoQuUPbmtcCQH/j+ubJrvBqlHhQ7TWxieKA0e
+dgoKCmJmI2HmdmSZ24H/gGL/AxpUlXnv6FmocuquhP6jAsDrsu7X/d/+UfxEnpr
Fqx8MDCFGAGzLJz4Vd4feny0EqqtbyVHqO8USfKTTLVU1uX7ysARtKMh/H+c1YrM
bYzEoSnztUetjv1f9obXG/6rxgxx7FHWAz+yWbDphyuvjnYWmNvl2zYcnPqOn748
GGKR3zIGd1bx1pExrC9KzLtp194VfEIO/xOaEZGdWDrb/hiLVr/bd9bRwDxqjNfZ
TU+Uw6SlGVwEs4JJtmdDJzefJW5ihVt4Am0FgfGoeUlLYUciUDkotCPT+y2AtuA=
=iyvU
-----END PGP SIGNATURE-----

