Path: news.gmane.org!not-for-mail
From: lgfmobile <lgfmobile-Re5JQEeQqe8AvxtiuMwx3w@public.gmane.org>
Newsgroups: gmane.linux.arch.brazil
Subject: Re: teclado para usuario adicionado
Date: Thu, 29 Dec 2011 09:04:20 -0200
Lines: 23
Approved: news@gmane.org
Message-ID: <4EFC4934.1060000@gmail.com>
References: <e0268ec1-4361-48bd-a8e9-9864c88373fb@l24g2000yqm.googlegroups.com>
Reply-To: archlinux-br-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org
NNTP-Posting-Host: lo.gmane.org
Mime-Version: 1.0
Content-Type: text/plain; charset=ISO-8859-1; format=flowed
Content-Transfer-Encoding: quoted-printable
X-Trace: dough.gmane.org 1325156513 32110 80.91.229.12 (29 Dec 2011 11:01:53 GMT)
X-Complaints-To: usenet@dough.gmane.org
NNTP-Posting-Date: Thu, 29 Dec 2011 11:01:53 +0000 (UTC)
To: archlinux-br-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org
Original-X-From: archlinux-br+bncCOGFzJqXAxCQkfH3BBoE8kiXlQ-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org Thu Dec 29 12:01:49 2011
Return-path: <archlinux-br+bncCOGFzJqXAxCQkfH3BBoE8kiXlQ-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>
Envelope-to: glab-archlinux-br@m.gmane.org
Original-Received: from mail-gy0-f186.google.com ([209.85.160.186])
	by lo.gmane.org with esmtp (Exim 4.69)
	(envelope-from <archlinux-br+bncCOGFzJqXAxCQkfH3BBoE8kiXlQ-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>)
	id 1RgDk2-00085E-RF
	for glab-archlinux-br@m.gmane.org; Thu, 29 Dec 2011 12:01:46 +0100
Original-Received: by ghbf1 with SMTP id f1sf4074683ghb.3
        for <glab-archlinux-br@m.gmane.org>; Thu, 29 Dec 2011 03:01:46 -0800 (PST)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=googlegroups.com; s=beta;
        h=x-beenthere:received-spf:message-id:date:from:user-agent
         :mime-version:to:subject:references:in-reply-to:x-original-sender
         :x-original-authentication-results:reply-to:precedence:mailing-list
         :list-id:x-google-group-id:list-post:list-help:list-archive:sender
         :list-subscribe:list-unsubscribe:content-type
         :content-transfer-encoding;
        bh=FDgfzDmnu2xU7XGSzDvBQQ1vXurX7vm5HvgC1XtMSTI=;
        b=TKjDH0Xxn8au0qE3fuP9xnlvS0qrPMxusjTyryinUugMCF4Rui2vc7Oh6RrhzbZCU5
         V0EH8zYdx5iRZLL1tZ3NE8JaWgJIQo34FOr0EZWXeKpGosGx5CMYduTj0Z3h0ZhatWbr
         UBNuCnbV314YhSMripBtnXyXneF0+XvNGMQ4E=
Original-Received: by 10.236.174.4 with SMTP id w4mr5376929yhl.10.1325156496367;
        Thu, 29 Dec 2011 03:01:36 -0800 (PST)
X-BeenThere: archlinux-br-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org
Original-Received: by 10.100.234.27 with SMTP id g27ls5017150anh.0.gmail; Thu, 29 Dec
 2011 03:01:35 -0800 (PST)
Original-Received: by 10.236.174.100 with SMTP id w64mr860629yhl.4.1325156495746;
        Thu, 29 Dec 2011 03:01:35 -0800 (PST)
Original-Received: by 10.236.174.100 with SMTP id w64mr860628yhl.4.1325156495736;
        Thu, 29 Dec 2011 03:01:35 -0800 (PST)
Original-Received: from mail-yx0-f178.google.com (mail-yx0-f178.google.com [209.85.213.178])
        by gmr-mx.google.com with ESMTPS id j50si11286528yhm.6.2011.12.29.03.01.35
        (version=TLSv1/SSLv3 cipher=OTHER);
        Thu, 29 Dec 2011 03:01:35 -0800 (PST)
Received-SPF: pass (google.com: domain of lgfmobile-Re5JQEeQqe8AvxtiuMwx3w@public.gmane.org designates 209.85.213.178 as permitted sender) client-ip=209.85.213.178;
Original-Received: by yenm5 with SMTP id m5so7070154yen.9
        for <archlinux-br-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>; Thu, 29 Dec 2011 03:01:35 -0800 (PST)
Original-Received: by 10.236.191.5 with SMTP id f5mr46920905yhn.122.1325156495663;
        Thu, 29 Dec 2011 03:01:35 -0800 (PST)
Original-Received: from [192.168.0.141] (200-232-149-239.dsl.telesp.net.br. [200.232.149.239])
        by mx.google.com with ESMTPS id m38sm83234403anq.16.2011.12.29.03.01.33
        (version=SSLv3 cipher=OTHER);
        Thu, 29 Dec 2011 03:01:34 -0800 (PST)
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:9.0) Gecko/20111224 Thunderbird/9.0.1
In-Reply-To: <e0268ec1-4361-48bd-a8e9-9864c88373fb-dFne0XOYxAtWAgDpVid4H2B/v6IoIuQBVpNB7YpNyf8@public.gmane.org>
X-Original-Sender: lgfmobile-Re5JQEeQqe8AvxtiuMwx3w@public.gmane.org
X-Original-Authentication-Results: gmr-mx.google.com; spf=pass (google.com:
 domain of lgfmobile-Re5JQEeQqe8AvxtiuMwx3w@public.gmane.org designates 209.85.213.178 as permitted sender)
 smtp.mail=lgfmobile-Re5JQEeQqe8AvxtiuMwx3w@public.gmane.org; dkim=pass (test mode) header.i=@gmail.com
Precedence: list
Mailing-list: list archlinux-br-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org; contact archlinux-br+owners-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org
List-ID: <archlinux-br.googlegroups.com>
X-Google-Group-Id: 926417450308
List-Post: <http://groups.google.com/group/archlinux-br/post?hl=pt-BR_US>, <mailto:archlinux-br-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>
List-Help: <http://groups.google.com/support/?hl=pt-BR_US>, <mailto:archlinux-br+help-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>
List-Archive: <http://groups.google.com/group/archlinux-br?hl=pt-BR_US>
Original-Sender: archlinux-br-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org
List-Subscribe: <http://groups.google.com/group/archlinux-br/subscribe?hl=pt-BR_US>,
 <mailto:archlinux-br+subscribe-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>
List-Unsubscribe: <http://groups.google.com/group/archlinux-br/subscribe?hl=pt-BR_US>,
 <mailto:archlinux-br+unsubscribe-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>
Xref: news.gmane.org gmane.linux.arch.brazil:6205
Archived-At: <http://permalink.gmane.org/gmane.linux.arch.brazil/6205>

Em 29-12-2011 01:33, Reinaldo escreveu:
> Prezados,
> criei um usuario e nao estou conseguindo configurar o teclado dele.
> Tanto o rc.conf como o locale.gen estao com as opcoes corretas.
>
> Alguem pode me ajudar?
> Obrigado.
>
Qual ambiente gr=E1fico ?

--=20
Voc=EA recebeu esta mensagem porque voc=EA se inscreveu no lista de dicuss=
=E3o do projeto Arch Linux Brasil - http://groups.google.com/group/archlinu=
x-br=20
Maiores informa=E7=F5es e novidades sobre o projeto podem ser vistas em htt=
p://www.archlinux-br.org
Para mandar mensagens para o grupo use o email archlinux-br-/JYPxA39Uh4Ykp1iOSErHA@public.gmane.org=
m. Lembre-se que somente membros podem postar mensagens.
Para se desinscrever deste grupo, envie um email para archlinux-br-unsubscr=
ibe-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org
Para mais op=E7=F5es. visite este grupo em http://groups.google.com/group/a=
rchlinux-br

