Path: news.gmane.org!not-for-mail
From: Stefan Wilkens <stefanwilkens-Re5JQEeQqe8AvxtiuMwx3w@public.gmane.org>
Newsgroups: gmane.linux.arch.tur.user
Subject: [Removal Request] yacy-svn
Date: Fri, 30 Dec 2011 12:35:59 +0100
Lines: 8
Approved: news@gmane.org
Message-ID: <CA+4o_oG7HjrjM57yO5h9xUAnXKaXZW8-Tow2q7Dd5RmJn7D+cw@mail.gmail.com>
Reply-To: "Discussion about the Arch User Repository \(AUR\)"
 <aur-general-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>
NNTP-Posting-Host: lo.gmane.org
Mime-Version: 1.0
Content-Type: text/plain; charset=ISO-8859-1
X-Trace: dough.gmane.org 1325244970 498 80.91.229.12 (30 Dec 2011 11:36:10 GMT)
X-Complaints-To: usenet@dough.gmane.org
NNTP-Posting-Date: Fri, 30 Dec 2011 11:36:10 +0000 (UTC)
To: "Discussion about the Arch User Repository (AUR)"
 <aur-general-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>
Original-X-From: aur-general-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org Fri Dec 30 12:36:06 2011
Return-path: <aur-general-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>
Envelope-to: glatu-tur-users@m.gmane.org
Original-Received: from gerolde.archlinux.org ([66.211.214.132])
	by lo.gmane.org with esmtp (Exim 4.69)
	(envelope-from <aur-general-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>)
	id 1Rgako-0002nh-6r
	for glatu-tur-users@m.gmane.org; Fri, 30 Dec 2011 12:36:06 +0100
Original-Received: from gudrun.archlinux.org (gudrun.archlinux.org [66.211.214.131])
	by gerolde.archlinux.org (Postfix) with ESMTP id 894799015C;
	Fri, 30 Dec 2011 06:35:59 -0500 (EST)
Original-Received: from gerolde.archlinux.org (gerolde.archlinux.org [66.211.214.132])
 by gudrun.archlinux.org (Postfix) with ESMTP id 5587C86179
 for <aur-general-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>; Fri, 30 Dec 2011 06:35:58 -0500 (EST)
Received-SPF: pass (gmail.com ... _spf.google.com: 209.85.215.172 is
 authorized to use 'stefanwilkens-Re5JQEeQqe8AvxtiuMwx3w@public.gmane.org' in 'mfrom' identity (mechanism
 'ip4:209.85.128.0/17' matched)) receiver=gerolde.archlinux.org;
 identity=mailfrom; envelope-from="stefanwilkens-Re5JQEeQqe8AvxtiuMwx3w@public.gmane.org";
 helo=mail-ey0-f172.google.com; client-ip=209.85.215.172
Original-Received: from mail-ey0-f172.google.com (mail-ey0-f172.google.com
 [209.85.215.172])
 by gerolde.archlinux.org (Postfix) with ESMTPS id 129F190157
 for <aur-general-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>; Fri, 30 Dec 2011 06:35:57 -0500 (EST)
Original-Received: by eaak10 with SMTP id k10so5446596eaa.3
 for <aur-general-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>; Fri, 30 Dec 2011 03:36:00 -0800 (PST)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=gmail.com; s=gamma;
 h=mime-version:date:message-id:subject:from:to:content-type;
 bh=k+4LViN02fYF3CfDljafNk7DSk4S3ai+09+qGxbh28w=;
 b=wAsQs1Y5B3MAPyoecje9RZOF3lIAw/6K4cQ7jYyzb76yC6mvr2HGTAiADUV2F1bO7q
 UzgRUZwR6lhET3AdckDRiMNMtOEVBfum2UaS9AJfdGKdYJErJjsKpYOcsfX+yH9d2JAu
 VwQ7PG1VXdfCaxEDUKyHzJo/hspDXQBSyldcY=
Original-Received: by 10.213.4.82 with SMTP id 18mr877346ebq.49.1325244959403; Fri, 30
 Dec 2011 03:35:59 -0800 (PST)
Original-Received: by 10.213.15.16 with HTTP; Fri, 30 Dec 2011 03:35:59 -0800 (PST)
X-BeenThere: aur-general-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org
X-Mailman-Version: 2.1.14
Precedence: list
List-Id: "Discussion about the Arch User Repository \(AUR\)"
 <aur-general.archlinux.org>
List-Unsubscribe: <http://mailman.archlinux.org/mailman/options/aur-general>, 
 <mailto:aur-general-request-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org?subject=unsubscribe>
List-Archive: <http://mailman.archlinux.org/pipermail/aur-general>
List-Post: <mailto:aur-general-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org>
List-Help: <mailto:aur-general-request-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org?subject=help>
List-Subscribe: <http://mailman.archlinux.org/mailman/listinfo/aur-general>,
 <mailto:aur-general-request-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org?subject=subscribe>
Errors-To: aur-general-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org
Original-Sender: aur-general-bounces-fd97jBR+K/6hPH1hqNUYSQ@public.gmane.org
Xref: news.gmane.org gmane.linux.arch.tur.user:23277
Archived-At: <http://permalink.gmane.org/gmane.linux.arch.tur.user/23277>

Hi,

The yacy project moved to gitorious[1], the yacy-svn package[2] is no
longer valid and should be removed.

[1] https://gitorious.org/yacy
[2] https://aur.archlinux.org/packages.php?ID=14464

