Path: news.gmane.org!not-for-mail
From: Magnus Therning <magnus@therning.org>
Newsgroups: gmane.linux.arch.general
Subject: unionfs or aufs, available somewhere?
Date: Tue, 3 Jan 2012 11:26:10 +0100
Lines: 16
Approved: news@gmane.org
Message-ID: <CAAExw5ugL-Xb4tbdp29VhLbXMcUB7G0nWSw=FH+icuK3-R9w4g@mail.gmail.com>
Reply-To: General Discussion about Arch Linux <arch-general@archlinux.org>
NNTP-Posting-Host: lo.gmane.org
Mime-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable
X-Trace: dough.gmane.org 1325586381 7516 80.91.229.12 (3 Jan 2012 10:26:21 GMT)
X-Complaints-To: usenet@dough.gmane.org
NNTP-Posting-Date: Tue, 3 Jan 2012 10:26:21 +0000 (UTC)
To: General Discusson about Arch Linux <arch-general@archlinux.org>
Original-X-From: arch-general-bounces@archlinux.org Tue Jan 03 11:26:16 2012
Return-path: <arch-general-bounces@archlinux.org>
Envelope-to: glag-arch@m.gmane.org
Original-Received: from gerolde.archlinux.org ([66.211.214.132])
	by lo.gmane.org with esmtp (Exim 4.69)
	(envelope-from <arch-general-bounces@archlinux.org>)
	id 1Ri1ZQ-0005Ka-5f
	for glag-arch@m.gmane.org; Tue, 03 Jan 2012 11:26:16 +0100
Original-Received: from gudrun.archlinux.org (gudrun.archlinux.org [66.211.214.131])
	by gerolde.archlinux.org (Postfix) with ESMTP id 26FA9900DB;
	Tue,  3 Jan 2012 05:26:09 -0500 (EST)
Original-Received: from gerolde.archlinux.org (gerolde.archlinux.org [66.211.214.132])
 by gudrun.archlinux.org (Postfix) with ESMTP id 9F22186180
 for <arch-general@archlinux.org>; Tue,  3 Jan 2012 05:26:07 -0500 (EST)
Received-SPF: none (therning.org: No applicable sender policy available)
 receiver=gerolde.archlinux.org; identity=mailfrom;
 envelope-from="magnus@therning.org"; helo=mail-lpp01m010-f44.google.com;
 client-ip=209.85.215.44
Original-Received: from mail-lpp01m010-f44.google.com (mail-lpp01m010-f44.google.com
 [209.85.215.44])
 by gerolde.archlinux.org (Postfix) with ESMTPS id 51CA3900D6
 for <arch-general@archlinux.org>; Tue,  3 Jan 2012 05:26:06 -0500 (EST)
Original-Received: by laah2 with SMTP id h2so5803575laa.3
 for <arch-general@archlinux.org>; Tue, 03 Jan 2012 02:26:10 -0800 (PST)
Original-Received: by 10.152.134.10 with SMTP id pg10mr41909382lab.3.1325586370097;
 Tue, 03 Jan 2012 02:26:10 -0800 (PST)
Original-Received: by 10.152.162.103 with HTTP; Tue, 3 Jan 2012 02:26:10 -0800 (PST)
X-BeenThere: arch-general@archlinux.org
X-Mailman-Version: 2.1.14
Precedence: list
List-Id: General Discussion about Arch Linux <arch-general.archlinux.org>
List-Unsubscribe: <http://mailman.archlinux.org/mailman/options/arch-general>, 
 <mailto:arch-general-request@archlinux.org?subject=unsubscribe>
List-Archive: <http://mailman.archlinux.org/pipermail/arch-general>
List-Post: <mailto:arch-general@archlinux.org>
List-Help: <mailto:arch-general-request@archlinux.org?subject=help>
List-Subscribe: <http://mailman.archlinux.org/mailman/listinfo/arch-general>, 
 <mailto:arch-general-request@archlinux.org?subject=subscribe>
Errors-To: arch-general-bounces@archlinux.org
Original-Sender: arch-general-bounces@archlinux.org
Xref: news.gmane.org gmane.linux.arch.general:38519
Archived-At: <http://permalink.gmane.org/gmane.linux.arch.general/38519>

Is either of them easily available somewhere?

I'd like to use the `union-type=3D` option of `schroot`, but so far it
looks like I'll have to get a new kernel from AUR and compile aufs3
myself to set it up.  Is neither of these rather useful filesystems
available pre-built somewhere?

/M

--=20
Magnus Therning =C2=A0 =C2=A0 =C2=A0 =C2=A0 =C2=A0 =C2=A0 =C2=A0 =C2=A0 =C2=
=A0 =C2=A0 =C2=A0OpenPGP: 0xAB4DFBA4
email: magnus@therning.org =C2=A0 jabber: magnus@therning.org
twitter: magthe =C2=A0 =C2=A0 =C2=A0 =C2=A0 =C2=A0 =C2=A0 =C2=A0 http://the=
rning.org/magnus

