Path: news.gmane.org!not-for-mail
From: =?UTF-8?Q?Denis_A=2E_Alto=C3=A9_Falqueto?= <denisfalqueto-Re5JQEeQqe8AvxtiuMwx3w@public.gmane.org>
Newsgroups: gmane.linux.arch.brazil
Subject: Top posting
Date: Fri, 16 Dec 2011 00:50:46 -0200
Lines: 73
Approved: news@gmane.org
Message-ID: <CACQH-_z2gxwMOtJGx=ckgbwfgV1pYN5LR83yJXFh_YMm5oHycg@mail.gmail.com>
Reply-To: archlinux-br-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org
NNTP-Posting-Host: lo.gmane.org
Mime-Version: 1.0
Content-Type: text/plain; charset=ISO-8859-1
Content-Transfer-Encoding: quoted-printable
X-Trace: dough.gmane.org 1324003878 9826 80.91.229.12 (16 Dec 2011 02:51:18 GMT)
X-Complaints-To: usenet@dough.gmane.org
NNTP-Posting-Date: Fri, 16 Dec 2011 02:51:18 +0000 (UTC)
To: archlinux-br-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org
Original-X-From: archlinux-br+bncCPiZ-_v4DBCY5Kr3BBoEL3uiCg-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org Fri Dec 16 03:51:14 2011
Return-path: <archlinux-br+bncCPiZ-_v4DBCY5Kr3BBoEL3uiCg-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>
Envelope-to: glab-archlinux-br@m.gmane.org
Original-Received: from mail-ey0-f186.google.com ([209.85.215.186])
	by lo.gmane.org with esmtp (Exim 4.69)
	(envelope-from <archlinux-br+bncCPiZ-_v4DBCY5Kr3BBoEL3uiCg-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>)
	id 1RbNtB-00021s-Vr
	for glab-archlinux-br@m.gmane.org; Fri, 16 Dec 2011 03:51:14 +0100
Original-Received: by eaac13 with SMTP id c13sf2227380eaa.3
        for <glab-archlinux-br@m.gmane.org>; Thu, 15 Dec 2011 18:51:13 -0800 (PST)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=googlegroups.com; s=beta;
        h=x-beenthere:received-spf:mime-version:from:date:message-id:subject
         :to:x-original-sender:x-original-authentication-results:reply-to
         :precedence:mailing-list:list-id:x-google-group-id:list-post
         :list-help:list-archive:sender:list-subscribe:list-unsubscribe
         :content-type:content-transfer-encoding;
        bh=PGbffHmK8UIPpVpuuUGMSFixeCsx36Z0tUMVzagM+JE=;
        b=4vzh5TvkqEj5vtbhsZAPhWJdmkd7MP/IX7Y/h5uEZoq648gjRq/3pXnpcLf2TAYxwt
         ksmc4h2H2paIVvS0sQd+HycDHEt4ybkO50D0Aw8vpKzeF+Q5VvG/d5ceSPTfS9bgtXyf
         +ATAylOw0wK2mfAWtV0ecbKoBP60DAqCjwPEQ=
Original-Received: by 10.204.166.66 with SMTP id l2mr949884bky.34.1324003864324;
        Thu, 15 Dec 2011 18:51:04 -0800 (PST)
X-BeenThere: archlinux-br-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org
Original-Received: by 10.213.102.203 with SMTP id h11ls2200374ebo.3.gmail; Thu, 15 Dec
 2011 18:51:02 -0800 (PST)
Original-Received: by 10.14.124.73 with SMTP id w49mr1074419eeh.4.1324003862721;
        Thu, 15 Dec 2011 18:51:02 -0800 (PST)
Original-Received: by 10.14.124.73 with SMTP id w49mr1074418eeh.4.1324003862708;
        Thu, 15 Dec 2011 18:51:02 -0800 (PST)
Original-Received: from mail-ey0-f175.google.com (mail-ey0-f175.google.com [209.85.215.175])
        by gmr-mx.google.com with ESMTPS id a53si5708702eeg.1.2011.12.15.18.51.02
        (version=TLSv1/SSLv3 cipher=OTHER);
        Thu, 15 Dec 2011 18:51:02 -0800 (PST)
Received-SPF: pass (google.com: domain of denisfalqueto-Re5JQEeQqe8AvxtiuMwx3w@public.gmane.org designates 209.85.215.175 as permitted sender) client-ip=209.85.215.175;
Original-Received: by eaal1 with SMTP id l1so3698192eaa.34
        for <archlinux-br-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>; Thu, 15 Dec 2011 18:51:02 -0800 (PST)
Original-Received: by 10.205.139.66 with SMTP id iv2mr2582188bkc.27.1324003862149; Thu,
 15 Dec 2011 18:51:02 -0800 (PST)
Original-Received: by 10.204.225.145 with HTTP; Thu, 15 Dec 2011 18:50:46 -0800 (PST)
X-Original-Sender: denisfalqueto-Re5JQEeQqe8AvxtiuMwx3w@public.gmane.org
X-Original-Authentication-Results: gmr-mx.google.com; spf=pass (google.com:
 domain of denisfalqueto-Re5JQEeQqe8AvxtiuMwx3w@public.gmane.org designates 209.85.215.175 as permitted
 sender) smtp.mail=denisfalqueto-Re5JQEeQqe8AvxtiuMwx3w@public.gmane.org; dkim=pass (test mode) header.i=@gmail.com
Precedence: list
Mailing-list: list archlinux-br-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org; contact archlinux-br+owners-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org
List-ID: <archlinux-br.googlegroups.com>
X-Google-Group-Id: 926417450308
List-Post: <http://groups.google.com/group/archlinux-br/post?hl=pt-BR_US>, <mailto:archlinux-br-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>
List-Help: <http://groups.google.com/support/?hl=pt-BR_US>, <mailto:archlinux-br+help-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>
List-Archive: <http://groups.google.com/group/archlinux-br?hl=pt-BR_US>
Original-Sender: archlinux-br-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org
List-Subscribe: <http://groups.google.com/group/archlinux-br/subscribe?hl=pt-BR_US>,
 <mailto:archlinux-br+subscribe-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>
List-Unsubscribe: <http://groups.google.com/group/archlinux-br/subscribe?hl=pt-BR_US>,
 <mailto:archlinux-br+unsubscribe-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>
Xref: news.gmane.org gmane.linux.arch.brazil:6164
Archived-At: <http://permalink.gmane.org/gmane.linux.arch.brazil/6164>

Pessoal, bom dia, boa tarde, boa noite.

Eu tenho acompanhado a lista Archlinux-br h=E1 um tempo e venho
reparando esse comportamento que me deixa meio incomodado...  J=E1
pensei em escrever v=E1rias vezes mas sempre achei que ia ser recha=E7ado
por parecer chato. Como isso talvez seja rediscutido na comunidade
Arch internacional[1], acho que vou aproveitar a oportunidade e falar
sobre isso aqui tamb=E9m.

- O que =E9 o top posting?

=C9 quando uma pessoa responde um email com a resposta antes do texto
que foi enviado originalmente.

- Porque isso =E9 ruim?

Leiam o excelente texto explicativo: http://idallen.com/topposting.html

Um outro motivo que n=E3o est=E1 no documento acima =E9 o registro das
mensagens. Nossas discuss=F5es ficar=E3o dispon=EDveis por muitos anos.
Daqui h=E1 algum tempo, uma pessoa vai encontrar um de nossos posts e
vai ficar completamente confusa com a discuss=E3o. No fim das contas,
ela tem que ler cada mensagem toda de novo, do come=E7o ao fim, pr=E1
entender se aquele email =E9 =FAtil ou n=E3o. J=E1 fiz isso v=E1rias vezes =
e
tenho certeza que voc=EAs tamb=E9m.

- Mas meu cliente de email ou webmail j=E1 bota o cursor piscando logo
acima da mensagem original... Vai me dar muito trabalho.

Sim, infelizmente... Eu uso o GMail sempre e ele faz isso. Mas n=E3o
custa muito mudar um mal h=E1bito. Depois do 5o. ou 6o. email que voc=EA
responder assim, voc=EA vai come=E7ar a ver que n=E3o =E9 tanto trabalho
assim. E a maioria dos clientes de email podem ser configurados para
colocar o texto ap=F3s a mensagem original.

Enfim, =E9 isso. Quero deixar claro que eu tamb=E9m j=E1 fiz top posting
muitas vezes, at=E9 que li um texto sobre etiqueta na internet
(infelizmente, n=E3o consegui achar esse texto, era muito bom). Depois
desse texto, percebi que valia a pena se esfor=E7ar um pouco pr=E1 ter uma
comunica=E7=E3o mais organizada.

Abra=E7os!

PS: prevejo gente respondendo com top posting. Mas se puderem evitar,
por favor, evitem :) J=E1 =E9 uma oportunidade de mudar o h=E1bito.

[1] https://mailman.archlinux.org/pipermail/arch-general/2011-December/0233=
78.html

--=20
R: Porque prejudica a legibilidade do texto.
P: Por que =E9 ruim colocar a resposta de um e-mail antes do texto citado?
Para mais informa=E7=F5es, leia: http://idallen.com/topposting.html

-------------------------------------------
Denis A. Altoe Falqueto
Linux user #524555
-------------------------------------------

--=20
Voc=EA recebeu esta mensagem porque voc=EA se inscreveu no lista de dicuss=
=E3o do projeto Arch Linux Brasil - http://groups.google.com/group/archlinu=
x-br=20
Maiores informa=E7=F5es e novidades sobre o projeto podem ser vistas em htt=
p://www.archlinux-br.org
Para mandar mensagens para o grupo use o email archlinux-br-/JYPxA39Uh4Ykp1iOSErHA@public.gmane.org=
m. Lembre-se que somente membros podem postar mensagens.
Para se desinscrever deste grupo, envie um email para archlinux-br-unsubscr=
ibe-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org
Para mais op=E7=F5es. visite este grupo em http://groups.google.com/group/a=
rchlinux-br

