Path: news.gmane.org!not-for-mail
From: Jonathan Vasquez <jvasquez1011@gmail.com>
Newsgroups: gmane.linux.arch.general
Subject: People that depend on Arch,
	etc deserve to die? - Allan McRae - Clarifications
Date: Fri, 23 Dec 2011 05:32:25 -0500
Lines: 27
Approved: news@gmane.org
Message-ID: <CAD+HWv8FW87iGC-H+Zk2t6rMgKk2jRzg15vxu49Ju_feOdeHWA@mail.gmail.com>
Reply-To: General Discussion about Arch Linux <arch-general@archlinux.org>
NNTP-Posting-Host: lo.gmane.org
Mime-Version: 1.0
Content-Type: text/plain; charset=ISO-8859-1
X-Trace: dough.gmane.org 1324636355 32263 80.91.229.12 (23 Dec 2011 10:32:35 GMT)
X-Complaints-To: usenet@dough.gmane.org
NNTP-Posting-Date: Fri, 23 Dec 2011 10:32:35 +0000 (UTC)
To: arch-general@archlinux.org
Original-X-From: arch-general-bounces@archlinux.org Fri Dec 23 11:32:31 2011
Return-path: <arch-general-bounces@archlinux.org>
Envelope-to: glag-arch@m.gmane.org
Original-Received: from gerolde.archlinux.org ([66.211.214.132])
	by lo.gmane.org with esmtp (Exim 4.69)
	(envelope-from <arch-general-bounces@archlinux.org>)
	id 1Re2QQ-0001GB-O4
	for glag-arch@m.gmane.org; Fri, 23 Dec 2011 11:32:30 +0100
Original-Received: from gudrun.archlinux.org (gudrun.archlinux.org [66.211.214.131])
	by gerolde.archlinux.org (Postfix) with ESMTP id 13E9790107;
	Fri, 23 Dec 2011 05:32:26 -0500 (EST)
Original-Received: from gerolde.archlinux.org (gerolde.archlinux.org [66.211.214.132])
 by gudrun.archlinux.org (Postfix) with ESMTP id CB5CA86163
 for <arch-general@archlinux.org>; Fri, 23 Dec 2011 05:32:24 -0500 (EST)
Received-SPF: pass (gmail.com ... _spf.google.com: 209.85.220.172 is
 authorized to use 'jvasquez1011@gmail.com' in 'mfrom' identity (mechanism
 'ip4:209.85.128.0/17' matched)) receiver=gerolde.archlinux.org;
 identity=mailfrom; envelope-from="jvasquez1011@gmail.com";
 helo=mail-vx0-f172.google.com; client-ip=209.85.220.172
Original-Received: from mail-vx0-f172.google.com (mail-vx0-f172.google.com
 [209.85.220.172])
 by gerolde.archlinux.org (Postfix) with ESMTPS id BA36A900FC
 for <arch-general@archlinux.org>; Fri, 23 Dec 2011 05:32:24 -0500 (EST)
Original-Received: by vcbfk13 with SMTP id fk13so7010378vcb.3
 for <arch-general@archlinux.org>; Fri, 23 Dec 2011 02:32:25 -0800 (PST)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=gmail.com; s=gamma;
 h=mime-version:date:message-id:subject:from:to:content-type;
 bh=Zy9092uThSjSTwyo3d80Ruo6/c97Hfetwf1iLzLbl3c=;
 b=ry881e564oWu6Lj+wUr0gws9w9a85dGNc6vVoua7Mxk3MIZ6to5L3DAtslM7gMewf7
 8n7OqJl48DzS0LD15GSLBsHQBpY/17vcVuyGRB423/y+kYyY1qU6sEEXPIIhoB8+LAjN
 pPwJ7kVTtSozMdTI5GpEc60OOmFXna7uz9jcY=
Original-Received: by 10.52.94.148 with SMTP id dc20mr7458697vdb.109.1324636345430;
 Fri, 23 Dec 2011 02:32:25 -0800 (PST)
Original-Received: by 10.52.30.231 with HTTP; Fri, 23 Dec 2011 02:32:25 -0800 (PST)
X-Content-Filtered-By: Mailman/MimeDel 2.1.14
X-BeenThere: arch-general@archlinux.org
X-Mailman-Version: 2.1.14
Precedence: list
List-Id: General Discussion about Arch Linux <arch-general.archlinux.org>
List-Unsubscribe: <http://mailman.archlinux.org/mailman/options/arch-general>, 
 <mailto:arch-general-request@archlinux.org?subject=unsubscribe>
List-Archive: <http://mailman.archlinux.org/pipermail/arch-general>
List-Post: <mailto:arch-general@archlinux.org>
List-Help: <mailto:arch-general-request@archlinux.org?subject=help>
List-Subscribe: <http://mailman.archlinux.org/mailman/listinfo/arch-general>, 
 <mailto:arch-general-request@archlinux.org?subject=subscribe>
Errors-To: arch-general-bounces@archlinux.org
Original-Sender: arch-general-bounces@archlinux.org
Xref: news.gmane.org gmane.linux.arch.general:38383
Archived-At: <http://permalink.gmane.org/gmane.linux.arch.general/38383>

Hello everyone,

I was reading the package signing discussion that was going on over at the
[pacman-dev] mailing list
http://mailman.archlinux.org/pipermail/pacman-dev/2011-February/012483.html

and Allan said the following:

"I think I know every distribution using pacman as a package manager and

(unless there is an enterprise level distro I am missing) if peoples
lives depend on one of these distros, then I am sorry to say it but in
my opinion they are stupid and deserve to die."


I wanted to know what was he trying to say? Is he saying that Arch and
other Arch-like distros aren't serious distros that aren't meant for
production? I mean I understand that Arch is rolling release and all
that, but it's packages are marked stable by their corresponding
upstreams.

What are your opinions about this?


-- 
Jonathan Vasquez

