Path: news.gmane.org!not-for-mail
From: "ali.mousavi@gmail.com" <ali.mousavi@gmail.com>
Newsgroups: gmane.linux.arch.general
Subject: Re: Is there a clean solution to get completely rid
	of Pulseaudio?
Date: Fri, 23 Dec 2011 13:02:30 +0330
Lines: 3
Approved: news@gmane.org
Message-ID: <CAD5P+LZG6X=XmJYzBvn35wqAy9UQx9LWUvi6Anv_CLEGR7zmmw@mail.gmail.com>
References: <1324629697.9930.38.camel@localhost.localdomain>
 <4EF44735.8050009@archlinux.org>
 <1324632316.9930.45.camel@localhost.localdomain>
 <4EF44980.8060609@archlinux.org>
Reply-To: General Discussion about Arch Linux <arch-general@archlinux.org>
NNTP-Posting-Host: lo.gmane.org
Mime-Version: 1.0
Content-Type: text/plain; charset=UTF-8
X-Trace: dough.gmane.org 1324632784 8847 80.91.229.12 (23 Dec 2011 09:33:04 GMT)
X-Complaints-To: usenet@dough.gmane.org
NNTP-Posting-Date: Fri, 23 Dec 2011 09:33:04 +0000 (UTC)
To: General Discussion about Arch Linux <arch-general@archlinux.org>
Original-X-From: arch-general-bounces@archlinux.org Fri Dec 23 10:33:01 2011
Return-path: <arch-general-bounces@archlinux.org>
Envelope-to: glag-arch@m.gmane.org
Original-Received: from gerolde.archlinux.org ([66.211.214.132])
	by lo.gmane.org with esmtp (Exim 4.69)
	(envelope-from <arch-general-bounces@archlinux.org>)
	id 1Re1Un-0005yq-3r
	for glag-arch@m.gmane.org; Fri, 23 Dec 2011 10:32:57 +0100
Original-Received: from gudrun.archlinux.org (gudrun.archlinux.org [66.211.214.131])
	by gerolde.archlinux.org (Postfix) with ESMTP id CD58290059;
	Fri, 23 Dec 2011 04:32:52 -0500 (EST)
Original-Received: from gerolde.archlinux.org (gerolde.archlinux.org [66.211.214.132])
 by gudrun.archlinux.org (Postfix) with ESMTP id 464EE86163
 for <arch-general@archlinux.org>; Fri, 23 Dec 2011 04:32:51 -0500 (EST)
Received-SPF: pass (gmail.com ... _spf.google.com: 209.85.210.44 is authorized
 to use 'ali.mousavi@gmail.com' in 'mfrom' identity (mechanism
 'ip4:209.85.128.0/17' matched)) receiver=gerolde.archlinux.org;
 identity=mailfrom; envelope-from="ali.mousavi@gmail.com";
 helo=mail-pz0-f44.google.com; client-ip=209.85.210.44
Original-Received: from mail-pz0-f44.google.com (mail-pz0-f44.google.com
 [209.85.210.44])
 by gerolde.archlinux.org (Postfix) with ESMTPS id 0F37D90043
 for <arch-general@archlinux.org>; Fri, 23 Dec 2011 04:32:50 -0500 (EST)
Original-Received: by dajz8 with SMTP id z8so6264915daj.3
 for <arch-general@archlinux.org>; Fri, 23 Dec 2011 01:32:51 -0800 (PST)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=gmail.com; s=gamma;
 h=mime-version:in-reply-to:references:from:date:message-id:subject:to
 :content-type; bh=vQBou6We4jANiKeCPHqyrGB6WPD9vcQOJDKWP6BTuyk=;
 b=WEU8XrzunlisX08yTlle9Rh73PM3kZ8KfUTYVnWlLyXZ11cLixWclqyqz4t4wzVLc/
 RKj4vi8YXQfrlhlTXDUWp3pVLfRzGistu8yM+4qHK449e8zi4hIk87zfANmgJ9OVR7Eq
 B3nW8VXdtblG3SBtvYKdFzbm4iqz3xe9VatIo=
Original-Received: by 10.68.122.132 with SMTP id ls4mr7383192pbb.17.1324632771269; Fri,
 23 Dec 2011 01:32:51 -0800 (PST)
Original-Received: by 10.68.48.227 with HTTP; Fri, 23 Dec 2011 01:32:30 -0800 (PST)
In-Reply-To: <4EF44980.8060609@archlinux.org>
X-Content-Filtered-By: Mailman/MimeDel 2.1.14
X-BeenThere: arch-general@archlinux.org
X-Mailman-Version: 2.1.14
Precedence: list
List-Id: General Discussion about Arch Linux <arch-general.archlinux.org>
List-Unsubscribe: <http://mailman.archlinux.org/mailman/options/arch-general>, 
 <mailto:arch-general-request@archlinux.org?subject=unsubscribe>
List-Archive: <http://mailman.archlinux.org/pipermail/arch-general>
List-Post: <mailto:arch-general@archlinux.org>
List-Help: <mailto:arch-general-request@archlinux.org?subject=help>
List-Subscribe: <http://mailman.archlinux.org/mailman/listinfo/arch-general>, 
 <mailto:arch-general-request@archlinux.org?subject=subscribe>
Errors-To: arch-general-bounces@archlinux.org
Original-Sender: arch-general-bounces@archlinux.org
Xref: news.gmane.org gmane.linux.arch.general:38362
Archived-At: <http://permalink.gmane.org/gmane.linux.arch.general/38362>

you can't use gnome 3 without pulse audio. if you don't want to use pulse
audio, consider using another DE or WM.

