Path: news.gmane.org!not-for-mail
From: RCR <reinaldocezar-Re5JQEeQqe8AvxtiuMwx3w@public.gmane.org>
Newsgroups: gmane.linux.arch.brazil
Subject: Re: teclado para usuario adicionado
Date: Fri, 30 Dec 2011 17:42:37 -0200
Lines: 40
Approved: news@gmane.org
Message-ID: <CAEXYz25wVuNZeh-v_43+8Bes-njOWooYUrsiJnmG_DL7SgPgng@mail.gmail.com>
References: <e0268ec1-4361-48bd-a8e9-9864c88373fb@l24g2000yqm.googlegroups.com>
	<4EFC4934.1060000@gmail.com>
Reply-To: archlinux-br-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org
NNTP-Posting-Host: lo.gmane.org
Mime-Version: 1.0
Content-Type: multipart/alternative; boundary=e89a8ff1c52a5dfe7504b5546f53
X-Trace: dough.gmane.org 1325274177 26619 80.91.229.12 (30 Dec 2011 19:42:57 GMT)
X-Complaints-To: usenet@dough.gmane.org
NNTP-Posting-Date: Fri, 30 Dec 2011 19:42:57 +0000 (UTC)
To: archlinux-br-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org
Original-X-From: archlinux-br+bncCMW94YS7ARCtqPj3BBoEACwRow-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org Fri Dec 30 20:42:53 2011
Return-path: <archlinux-br+bncCMW94YS7ARCtqPj3BBoEACwRow-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>
Envelope-to: glab-archlinux-br@m.gmane.org
Original-Received: from mail-pz0-f58.google.com ([209.85.210.58])
	by lo.gmane.org with esmtp (Exim 4.69)
	(envelope-from <archlinux-br+bncCMW94YS7ARCtqPj3BBoEACwRow-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>)
	id 1RgiLo-0004aY-Kp
	for glab-archlinux-br@m.gmane.org; Fri, 30 Dec 2011 20:42:48 +0100
Original-Received: by dang27 with SMTP id g27sf12184468dan.3
        for <glab-archlinux-br@m.gmane.org>; Fri, 30 Dec 2011 11:42:47 -0800 (PST)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=googlegroups.com; s=beta;
        h=x-beenthere:received-spf:mime-version:in-reply-to:references:date
         :message-id:subject:from:to:x-original-sender
         :x-original-authentication-results:reply-to:precedence:mailing-list
         :list-id:x-google-group-id:list-post:list-help:list-archive:sender
         :list-subscribe:list-unsubscribe:content-type;
        bh=G16BONwvFqihzsRYH6PNmur3s63eZeQE9aa39NUyHpg=;
        b=rJ1O3pYHoos8xBy+IT2qP3jZs3gYtqqvEX/rKwIkBqm5Yn3HlmxuQagHi8cscTWywJ
         E085bltutK9XEUzM0GPya5tb/QzN6ZnaSSlpNmSqcjv3W7P28iSPJYR6U5lKmIAaXkyP
         IQojlFqLHSvSxeOQzPIxXU/HDflYto2vvujmM=
Original-Received: by 10.68.74.136 with SMTP id t8mr6811222pbv.19.1325274157840;
        Fri, 30 Dec 2011 11:42:37 -0800 (PST)
X-BeenThere: archlinux-br-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org
Original-Received: by 10.68.11.197 with SMTP id s5ls37316568pbb.0.gmail; Fri, 30 Dec
 2011 11:42:37 -0800 (PST)
Original-Received: by 10.68.75.170 with SMTP id d10mr27841276pbw.6.1325274157283;
        Fri, 30 Dec 2011 11:42:37 -0800 (PST)
Original-Received: by 10.68.75.170 with SMTP id d10mr27841273pbw.6.1325274157274;
        Fri, 30 Dec 2011 11:42:37 -0800 (PST)
Original-Received: from mail-pw0-f53.google.com (mail-pw0-f53.google.com [209.85.160.53])
        by gmr-mx.google.com with ESMTPS id n6si47410941pbg.2.2011.12.30.11.42.37
        (version=TLSv1/SSLv3 cipher=OTHER);
        Fri, 30 Dec 2011 11:42:37 -0800 (PST)
Received-SPF: pass (google.com: domain of reinaldocezar-Re5JQEeQqe8AvxtiuMwx3w@public.gmane.org designates 209.85.160.53 as permitted sender) client-ip=209.85.160.53;
Original-Received: by pbds6 with SMTP id s6so18814007pbd.26
        for <archlinux-br-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>; Fri, 30 Dec 2011 11:42:37 -0800 (PST)
Original-Received: by 10.68.196.193 with SMTP id io1mr96598196pbc.19.1325274157153;
 Fri, 30 Dec 2011 11:42:37 -0800 (PST)
Original-Received: by 10.142.132.10 with HTTP; Fri, 30 Dec 2011 11:42:37 -0800 (PST)
In-Reply-To: <4EFC4934.1060000-Re5JQEeQqe8AvxtiuMwx3w@public.gmane.org>
X-Original-Sender: reinaldocezar-Re5JQEeQqe8AvxtiuMwx3w@public.gmane.org
X-Original-Authentication-Results: gmr-mx.google.com; spf=pass (google.com:
 domain of reinaldocezar-Re5JQEeQqe8AvxtiuMwx3w@public.gmane.org designates 209.85.160.53 as permitted
 sender) smtp.mail=reinaldocezar-Re5JQEeQqe8AvxtiuMwx3w@public.gmane.org; dkim=pass (test mode) header.i=@gmail.com
Precedence: list
Mailing-list: list archlinux-br-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org; contact archlinux-br+owners-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org
List-ID: <archlinux-br.googlegroups.com>
X-Google-Group-Id: 926417450308
List-Post: <http://groups.google.com/group/archlinux-br/post?hl=pt-BR_US>, <mailto:archlinux-br-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>
List-Help: <http://groups.google.com/support/?hl=pt-BR_US>, <mailto:archlinux-br+help-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>
List-Archive: <http://groups.google.com/group/archlinux-br?hl=pt-BR_US>
Original-Sender: archlinux-br-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org
List-Subscribe: <http://groups.google.com/group/archlinux-br/subscribe?hl=pt-BR_US>,
 <mailto:archlinux-br+subscribe-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>
List-Unsubscribe: <http://groups.google.com/group/archlinux-br/subscribe?hl=pt-BR_US>,
 <mailto:googlegroups-manage+926417450308+unsubscribe-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>
Xref: news.gmane.org gmane.linux.arch.brazil:6206
Archived-At: <http://permalink.gmane.org/gmane.linux.arch.brazil/6206>

--e89a8ff1c52a5dfe7504b5546f53
Content-Type: text/plain; charset=ISO-8859-1
Content-Transfer-Encoding: quoted-printable

KDE.

--=20
Voc=EA recebeu esta mensagem porque voc=EA se inscreveu no lista de dicuss=
=E3o do projeto Arch Linux Brasil - http://groups.google.com/group/archlinu=
x-br=20
Maiores informa=E7=F5es e novidades sobre o projeto podem ser vistas em htt=
p://www.archlinux-br.org
Para mandar mensagens para o grupo use o email archlinux-br-/JYPxA39Uh4Ykp1iOSErHA@public.gmane.org=
m. Lembre-se que somente membros podem postar mensagens.
Para se desinscrever deste grupo, envie um email para archlinux-br-unsubscr=
ibe-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org
Para mais op=E7=F5es. visite este grupo em http://groups.google.com/group/a=
rchlinux-br
--e89a8ff1c52a5dfe7504b5546f53
Content-Type: text/html; charset=ISO-8859-1
Content-Transfer-Encoding: quoted-printable

KDE.<br>

<p></p>

-- <br />
Voc=EA recebeu esta mensagem porque voc=EA se inscreveu no lista de dicuss=
=E3o do projeto Arch Linux Brasil - <a href=3D"http://groups.google.com/gro=
up/archlinux-br">http://groups.google.com/group/archlinux-br</a> <br />
Maiores informa=E7=F5es e novidades sobre o projeto podem ser vistas em <a =
href=3D"http://www.archlinux-br.org">http://www.archlinux-br.org</a><br />
Para mandar mensagens para o grupo use o email archlinux-br-/JYPxA39Uh4Ykp1iOSErHA@public.gmane.org=
m. Lembre-se que somente membros podem postar mensagens.<br />
Para se desinscrever deste grupo, envie um email para archlinux-br-unsubscr=
ibe-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org<br />
Para mais op=E7=F5es. visite este grupo em <a href=3D"http://groups.google.=
com/group/archlinux-br">http://groups.google.com/group/archlinux-br</a>
--e89a8ff1c52a5dfe7504b5546f53--

