Path: news.gmane.org!not-for-mail
From: Jari Sundell <sundell.software@gmail.com>
Newsgroups: gmane.network.bit-torrent.rtorrent.devel
Subject: Testing new mailinglist setup
Date: Sat, 5 Nov 2011 22:43:16 +0900
Lines: 3
Approved: news@gmane.org
Message-ID: <CAH1CXAGW4Lh6ebNFWC-O=FjGPdx7wG-t1C7QWxqv4OW64VoRZg@mail.gmail.com>
NNTP-Posting-Host: lo.gmane.org
Mime-Version: 1.0
Content-Type: text/plain; charset="us-ascii"
Content-Transfer-Encoding: 7bit
X-Trace: dough.gmane.org 1320501740 28003 80.91.229.12 (5 Nov 2011 14:02:20 GMT)
X-Complaints-To: usenet@dough.gmane.org
NNTP-Posting-Date: Sat, 5 Nov 2011 14:02:20 +0000 (UTC)
To: rtorrent mailinglist <libtorrent-devel@rakshasa.no>
Original-X-From: libtorrent-devel-bounces@rakshasa.no Sat Nov 05 15:02:14 2011
Return-path: <libtorrent-devel-bounces@rakshasa.no>
Envelope-to: gnbrd-libtorrent-devel@m.gmane.org
Original-Received: from li4-220.members.linode.com ([66.220.1.220] helo=rakshasa.no)
	by lo.gmane.org with esmtp (Exim 4.69)
	(envelope-from <libtorrent-devel-bounces@rakshasa.no>)
	id 1RMgoz-0006UT-R8
	for gnbrd-libtorrent-devel@m.gmane.org; Sat, 05 Nov 2011 15:02:10 +0100
Original-Received: from li4-220.members.linode.com (localhost.localdomain [127.0.0.1])
	by rakshasa.no (Postfix) with ESMTP id 07910478A9;
	Sat,  5 Nov 2011 10:02:08 -0400 (EDT)
X-Original-To: libtorrent-devel@rakshasa.no
Delivered-To: libtorrent-devel@rakshasa.no
Original-Received: from mail-ey0-f173.google.com (mail-ey0-f173.google.com
	[209.85.215.173]) (using TLSv1 with cipher RC4-SHA (128/128 bits))
	(No client certificate requested)
	by rakshasa.no (Postfix) with ESMTPS id 11E9447913
	for <libtorrent-devel@rakshasa.no>;
	Sat,  5 Nov 2011 09:43:17 -0400 (EDT)
Original-Received: by eyh6 with SMTP id 6so4046586eyh.18
	for <libtorrent-devel@rakshasa.no>;
	Sat, 05 Nov 2011 06:43:16 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=gmail.com; s=gamma;
	h=mime-version:date:message-id:subject:from:to:content-type;
	bh=lLU8UQb7CrINmKK0Gx+1GRxI206fR2BRWBC4/TCT+gw=;
	b=jY+faDz+70cis2/ue4OrVkyQT2ffr5qZ1V2ZO+alYVJCyqPq1ebLJoy/eel8QpsMer
	UahJJF7KKDoug8Kl4ZBOhVXS5JgW1gG1iYm3gJdEZOH1ko976V+i8UMA/U/82dD6apXb
	++7gHjhggtuFtZV1Ox9dgyUKmpPxsTdfKo2sk=
Original-Received: by 10.213.3.209 with SMTP id 17mr587801ebo.120.1320500596343; Sat,
	05 Nov 2011 06:43:16 -0700 (PDT)
Original-Received: by 10.213.17.83 with HTTP; Sat, 5 Nov 2011 06:43:16 -0700 (PDT)
X-BeenThere: libtorrent-devel@rakshasa.no
X-Mailman-Version: 2.1.13
Precedence: list
List-Id: libTorrent development <libtorrent-devel.rakshasa.no>
List-Unsubscribe: <http://rakshasa.no/mailman/options/libtorrent-devel>,
	<mailto:libtorrent-devel-request@rakshasa.no?subject=unsubscribe>
List-Archive: <http://rakshasa.no/pipermail/libtorrent-devel>
List-Post: <mailto:libtorrent-devel@rakshasa.no>
List-Help: <mailto:libtorrent-devel-request@rakshasa.no?subject=help>
List-Subscribe: <http://rakshasa.no/mailman/listinfo/libtorrent-devel>,
	<mailto:libtorrent-devel-request@rakshasa.no?subject=subscribe>
Original-Sender: libtorrent-devel-bounces@rakshasa.no
Errors-To: libtorrent-devel-bounces@rakshasa.no
Xref: news.gmane.org gmane.network.bit-torrent.rtorrent.devel:2502
Archived-At: <http://permalink.gmane.org/gmane.network.bit-torrent.rtorrent.devel/2502>

Checking if the new mailinlig configuration is working...

Jari Sundell
