Path: news.gmane.org!not-for-mail
From: Michael Sierchio <kudzu-vD6RicW5ZB5Wk0Htik3J/w@public.gmane.org>
Newsgroups: gmane.comp.sysutils.backup.tarsnap.user
Subject: All my archives are corrupt?
Date: Thu, 22 Dec 2011 08:41:26 -0800
Lines: 9
Approved: news@gmane.org
Message-ID: <CAHu1Y71byP9D3rfPL5900OmFw6hSXXiYxEPZDWczGmhgKYuo+w@mail.gmail.com>
NNTP-Posting-Host: lo.gmane.org
Mime-Version: 1.0
Content-Type: text/plain; charset=ISO-8859-1
X-Trace: dough.gmane.org 1324572100 6950 80.91.229.12 (22 Dec 2011 16:41:40 GMT)
X-Complaints-To: usenet@dough.gmane.org
NNTP-Posting-Date: Thu, 22 Dec 2011 16:41:40 +0000 (UTC)
To: tarsnap-users-C5KLY5ri3yZBDgjK7y7TUQ@public.gmane.org
Original-X-From: tarsnap-users-return-481-gcsbtu-tarsnap-users=m.gmane.org-C5KLY5ri3yZBDgjK7y7TUQ@public.gmane.org Thu Dec 22 17:41:37 2011
Return-path: <tarsnap-users-return-481-gcsbtu-tarsnap-users=m.gmane.org-C5KLY5ri3yZBDgjK7y7TUQ@public.gmane.org>
Envelope-to: gcsbtu-tarsnap-users-1dZseelyfdZg9hUCZPvPmw@public.gmane.org
Original-Received: from mx2.tarsnap.com ([208.79.82.75])
	by lo.gmane.org with smtp (Exim 4.69)
	(envelope-from <tarsnap-users-return-481-gcsbtu-tarsnap-users=m.gmane.org-C5KLY5ri3yZBDgjK7y7TUQ@public.gmane.org>)
	id 1Rdli2-0007d4-Kf
	for gcsbtu-tarsnap-users-1dZseelyfdZg9hUCZPvPmw@public.gmane.org; Thu, 22 Dec 2011 17:41:34 +0100
Original-Received: (qmail 4978 invoked from network); 22 Dec 2011 16:41:29 -0000
Original-Received: from unknown (HELO mx1.tarsnap.com) (192.168.0.25)
  by mx2.tarsnap.com with SMTP; 22 Dec 2011 16:41:29 -0000
Original-Received: (qmail 4756 invoked by uid 1025); 22 Dec 2011 16:41:27 -0000
Mailing-List: contact tarsnap-users-help-C5KLY5ri3yZBDgjK7y7TUQ@public.gmane.org; run by ezmlm
Precedence: bulk
List-Post: <mailto:tarsnap-users-C5KLY5ri3yZBDgjK7y7TUQ@public.gmane.org>
List-Help: <mailto:tarsnap-users-help-C5KLY5ri3yZBDgjK7y7TUQ@public.gmane.org>
List-Unsubscribe: <mailto:tarsnap-users-unsubscribe-C5KLY5ri3yZBDgjK7y7TUQ@public.gmane.org>
List-Subscribe: <mailto:tarsnap-users-subscribe-C5KLY5ri3yZBDgjK7y7TUQ@public.gmane.org>
Delivered-To: mailing list tarsnap-users-C5KLY5ri3yZBDgjK7y7TUQ@public.gmane.org
Original-Received: (qmail 4749 invoked from network); 22 Dec 2011 16:41:27 -0000
Xref: news.gmane.org gmane.comp.sysutils.backup.tarsnap.user:461
Archived-At: <http://permalink.gmane.org/gmane.comp.sysutils.backup.tarsnap.user/461>

smotrite 102# tarsnap -t -f daily.usr.20111221044126
tarsnap: *.log: Not found in archive
tarsnap: Error exit delayed from previous errors.

I've tried listing the contents of every archive for this host - same
result.  --fsck returns normal.

- M

