Path: news.gmane.org!not-for-mail
From: Justin Haynes <justin-+hlhkLlY5q4/t0gXnWhLCg@public.gmane.org>
Newsgroups: gmane.comp.sysutils.backup.tarsnap.user
Subject: iphone, Windows.
Date: Tue, 13 Dec 2011 18:01:46 -0600
Lines: 37
Approved: news@gmane.org
Message-ID: <CANSK4GDftsKwSJF1Sg0J3yKRvpjF2b2qH5AZGfdyF41FLYoOFg@mail.gmail.com>
NNTP-Posting-Host: lo.gmane.org
Mime-Version: 1.0
Content-Type: multipart/alternative; boundary=f46d041b47d6e7a8b804b4021205
X-Trace: dough.gmane.org 1323821031 30453 80.91.229.12 (14 Dec 2011 00:03:51 GMT)
X-Complaints-To: usenet@dough.gmane.org
NNTP-Posting-Date: Wed, 14 Dec 2011 00:03:51 +0000 (UTC)
To: tarsnap-users-C5KLY5ri3yZBDgjK7y7TUQ@public.gmane.org
Original-X-From: tarsnap-users-return-469-gcsbtu-tarsnap-users=m.gmane.org-C5KLY5ri3yZBDgjK7y7TUQ@public.gmane.org Wed Dec 14 01:03:47 2011
Return-path: <tarsnap-users-return-469-gcsbtu-tarsnap-users=m.gmane.org-C5KLY5ri3yZBDgjK7y7TUQ@public.gmane.org>
Envelope-to: gcsbtu-tarsnap-users-1dZseelyfdZg9hUCZPvPmw@public.gmane.org
Original-Received: from mx2.tarsnap.com ([208.79.82.75])
	by lo.gmane.org with smtp (Exim 4.69)
	(envelope-from <tarsnap-users-return-469-gcsbtu-tarsnap-users=m.gmane.org-C5KLY5ri3yZBDgjK7y7TUQ@public.gmane.org>)
	id 1RacK3-0001as-FJ
	for gcsbtu-tarsnap-users-1dZseelyfdZg9hUCZPvPmw@public.gmane.org; Wed, 14 Dec 2011 01:03:47 +0100
Original-Received: (qmail 8415 invoked from network); 14 Dec 2011 00:03:44 -0000
Original-Received: from unknown (HELO mx1.tarsnap.com) (192.168.0.25)
  by mx2.tarsnap.com with SMTP; 14 Dec 2011 00:03:44 -0000
Original-Received: (qmail 8221 invoked by uid 1025); 14 Dec 2011 00:03:43 -0000
Mailing-List: contact tarsnap-users-help-C5KLY5ri3yZBDgjK7y7TUQ@public.gmane.org; run by ezmlm
Precedence: bulk
List-Post: <mailto:tarsnap-users-C5KLY5ri3yZBDgjK7y7TUQ@public.gmane.org>
List-Help: <mailto:tarsnap-users-help-C5KLY5ri3yZBDgjK7y7TUQ@public.gmane.org>
List-Unsubscribe: <mailto:tarsnap-users-unsubscribe-C5KLY5ri3yZBDgjK7y7TUQ@public.gmane.org>
List-Subscribe: <mailto:tarsnap-users-subscribe-C5KLY5ri3yZBDgjK7y7TUQ@public.gmane.org>
Delivered-To: mailing list tarsnap-users-C5KLY5ri3yZBDgjK7y7TUQ@public.gmane.org
Delivered-To: moderator for tarsnap-users-C5KLY5ri3yZBDgjK7y7TUQ@public.gmane.org
Original-Received: (qmail 8086 invoked from network); 14 Dec 2011 00:01:47 -0000
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=gamma;
        h=mime-version:sender:date:x-google-sender-auth:message-id:subject
         :from:to:content-type;
        bh=jle+z0RuHUH4w3nToe/POQ0kuXuot1cqlyrm11ZFOZQ=;
        b=LW7hlrO6Okcg8olUbLBGjWHWCu/O9y/snrapPazdr74+Xa5ZX6rAbK6aoSrilXsdcd
         yonoKGYNf/lGa+Fy2XeKu2TPmBnOF4KFsMLsQBh15i1F2hJwliLCrd53Ljf4Eg/+hEZg
         v4dkZsAdo7+geE4j3LCVDbiEnWFdZ45ekD/t8=
Original-Sender: justinhenryhaynes-Re5JQEeQqe8AvxtiuMwx3w@public.gmane.org
X-Google-Sender-Auth: 72utQE121bw6qeAYEEJwar38xuE
Xref: news.gmane.org gmane.comp.sysutils.backup.tarsnap.user:449
Archived-At: <http://permalink.gmane.org/gmane.comp.sysutils.backup.tarsnap.user/449>

--f46d041b47d6e7a8b804b4021205
Content-Type: text/plain; charset=ISO-8859-1

1. Has anyone compiled tarsnap for iPhone?
Assuming a jailbroken iPhone with a user accessible shell and full access
to the filesystem with tarsnap potentially able to run as root, what
obstacles does anyone forsee in creating this?
I intend to jailbreak my verizon iPhone 4 soon, and I'd like to have the
ubiquity of being able to use tarsnap on any platforms.

2. Has anyone done a native compile of tarsnap on any of the Microsoft
platforms like Windows 7?  ( Or SCO?  :-) )



-Justin

--f46d041b47d6e7a8b804b4021205
Content-Type: text/html; charset=ISO-8859-1
Content-Transfer-Encoding: quoted-printable

<div>1. Has anyone compiled tarsnap for iPhone?</div>
<div>Assuming a jailbroken iPhone with a user accessible shell and full acc=
ess to the filesystem with tarsnap potentially able to run as root, what ob=
stacles does anyone forsee in creating this?</div>
<div>I intend to jailbreak my verizon iPhone 4 soon, and I&#39;d like to ha=
ve the ubiquity of being able to use tarsnap on any platforms.</div>
<div>=A0</div>
<div>2. Has anyone done a native compile of tarsnap on any of the Microsoft=
 platforms like Windows 7?=A0 ( Or SCO?=A0 :-)=A0)</div>
<div>=A0</div>
<div>=A0</div>
<div>=A0</div>
<div>-Justin</div>

--f46d041b47d6e7a8b804b4021205--

