Path: news.gmane.org!not-for-mail
From: Kleiton Kleber <moraes.kle-Re5JQEeQqe8AvxtiuMwx3w@public.gmane.org>
Newsgroups: gmane.linux.arch.brazil
Subject: =?ISO-8859-1?B?W2FyY2hsaW51eC1icl0gQXVtZW50YXIgYSBQYXJ0aefjbyAv?=
Date: Tue, 3 Jan 2012 00:32:20 -0300
Lines: 210
Approved: news@gmane.org
Message-ID: <CAPYTRd8baJCGcg0GEq6pww74xGYZrK1qo+D=ML_UWh+RyL3V9w@mail.gmail.com>
Reply-To: archlinux-br-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org
NNTP-Posting-Host: lo.gmane.org
Mime-Version: 1.0
Content-Type: multipart/alternative; boundary=14dae93997ddfca18704b597594a
X-Trace: dough.gmane.org 1325561578 5074 80.91.229.12 (3 Jan 2012 03:32:58 GMT)
X-Complaints-To: usenet@dough.gmane.org
NNTP-Posting-Date: Tue, 3 Jan 2012 03:32:58 +0000 (UTC)
To: archlinux-br-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org
Original-X-From: archlinux-br+bncCKyV7reqHhDa7Yn4BBoEEFRhPQ-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org Tue Jan 03 04:32:53 2012
Return-path: <archlinux-br+bncCKyV7reqHhDa7Yn4BBoEEFRhPQ-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>
Envelope-to: glab-archlinux-br@m.gmane.org
Original-Received: from mail-iy0-f186.google.com ([209.85.210.186])
	by lo.gmane.org with esmtp (Exim 4.69)
	(envelope-from <archlinux-br+bncCKyV7reqHhDa7Yn4BBoEEFRhPQ-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>)
	id 1Rhv7M-0005U9-PQ
	for glab-archlinux-br@m.gmane.org; Tue, 03 Jan 2012 04:32:53 +0100
Original-Received: by iahk25 with SMTP id k25sf64244269iah.3
        for <glab-archlinux-br@m.gmane.org>; Mon, 02 Jan 2012 19:32:51 -0800 (PST)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=googlegroups.com; s=beta;
        h=x-beenthere:received-spf:mime-version:from:date:message-id:subject
         :to:x-original-sender:x-original-authentication-results:reply-to
         :precedence:mailing-list:list-id:x-google-group-id:list-post
         :list-help:list-archive:sender:list-subscribe:list-unsubscribe
         :content-type;
        bh=+FeMnTX5mZreQmR6MJUWsYypHgH90TDum7amt8Z1cnQ=;
        b=JwS5g6py+kaIDXlZ6d+uC117rVoZpn5CXiywvjSavN/wNuk4sF7sVMfz+YlQAMhXgZ
         PR3AXlfOuN++qMAht9tOR7o8lG1QhRwAu1YCTgwKSBOREUaRhJD8CVOQRd4SNarHL89/
         xkh8OO9iRYSu81N5p+wPYF16uiSjU6jB0NsxI=
Original-Received: by 10.50.40.162 with SMTP id y2mr15092674igk.5.1325561562603;
        Mon, 02 Jan 2012 19:32:42 -0800 (PST)
X-BeenThere: archlinux-br-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org
Original-Received: by 10.231.58.10 with SMTP id e10ls479675ibh.5.gmail; Mon, 02 Jan
 2012 19:32:41 -0800 (PST)
Original-Received: by 10.42.163.65 with SMTP id b1mr31984450icy.2.1325561561603;
        Mon, 02 Jan 2012 19:32:41 -0800 (PST)
Original-Received: by 10.42.163.65 with SMTP id b1mr31984448icy.2.1325561561584;
        Mon, 02 Jan 2012 19:32:41 -0800 (PST)
Original-Received: from mail-tul01m020-f172.google.com (mail-tul01m020-f172.google.com [209.85.214.172])
        by gmr-mx.google.com with ESMTPS id at5si11577801igc.0.2012.01.02.19.32.41
        (version=TLSv1/SSLv3 cipher=OTHER);
        Mon, 02 Jan 2012 19:32:41 -0800 (PST)
Received-SPF: pass (google.com: domain of moraes.kle-Re5JQEeQqe8AvxtiuMwx3w@public.gmane.org designates 209.85.214.172 as permitted sender) client-ip=209.85.214.172;
Original-Received: by obcuz6 with SMTP id uz6so13972223obc.31
        for <archlinux-br-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>; Mon, 02 Jan 2012 19:32:41 -0800 (PST)
Original-Received: by 10.182.197.104 with SMTP id it8mr43566543obc.17.1325561561260;
 Mon, 02 Jan 2012 19:32:41 -0800 (PST)
Original-Received: by 10.182.46.42 with HTTP; Mon, 2 Jan 2012 19:32:20 -0800 (PST)
X-Original-Sender: moraes.kle-Re5JQEeQqe8AvxtiuMwx3w@public.gmane.org
X-Original-Authentication-Results: gmr-mx.google.com; spf=pass (google.com:
 domain of moraes.kle-Re5JQEeQqe8AvxtiuMwx3w@public.gmane.org designates 209.85.214.172 as permitted sender)
 smtp.mail=moraes.kle-Re5JQEeQqe8AvxtiuMwx3w@public.gmane.org; dkim=pass (test mode) header.i=@gmail.com
Precedence: list
Mailing-list: list archlinux-br-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org; contact archlinux-br+owners-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org
List-ID: <archlinux-br.googlegroups.com>
X-Google-Group-Id: 926417450308
List-Post: <http://groups.google.com/group/archlinux-br/post?hl=pt-BR_US>, <mailto:archlinux-br-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>
List-Help: <http://groups.google.com/support/?hl=pt-BR_US>, <mailto:archlinux-br+help-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>
List-Archive: <http://groups.google.com/group/archlinux-br?hl=pt-BR_US>
Original-Sender: archlinux-br-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org
List-Subscribe: <http://groups.google.com/group/archlinux-br/subscribe?hl=pt-BR_US>,
 <mailto:archlinux-br+subscribe-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>
List-Unsubscribe: <http://groups.google.com/group/archlinux-br/subscribe?hl=pt-BR_US>,
 <mailto:archlinux-br+unsubscribe-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>
Xref: news.gmane.org gmane.linux.arch.brazil:6214
Archived-At: <http://permalink.gmane.org/gmane.linux.arch.brazil/6214>

--14dae93997ddfca18704b597594a
Content-Type: text/plain; charset=windows-1252
Content-Transfer-Encoding: quoted-printable

Pessoal,

H=E1 algum problema em aumentar a parti=E7=E3o / ap=F3s o sistema est=E1 to=
do
configurado?
Acabei colocando muito pouco espa=E7o para a raiz j=E1 que em tese eu iria
formatar novamente por=E9m acabei ficando com "pregui=E7a" e deixei da form=
a
que est=E1.

k ~ $ df -h


Sist. Arq.       Tam  Usad Dispon. Uso% Montado em


rootfs          7,3G  6,4G    542M  93% /


udev             10M     0     10M   0% /dev


/run             10M  308K    9,7M   4% /run


/dev/sda3       7,3G  6,4G    542M  93% /


shm             1,9G  452K    1,9G   1% /dev/shm


tmpfs           1,9G  200K    1,9G   1% /tmp


/dev/sda4       451G  133G    296G  31% /home


/dev/sda1        99M   18M     77M  19% /boot


k ~ $

Obrigado.

--=20
Este e-mail pode conter anexos no formato ODF, um
padr=E3o aberto, gratuito e homologado pela ISO e
ABNT. Para visualizar ou editar, fa=E7a o download em
http://broffice.org/download e instale.

"...n=F3s n=E3o somos livres para deixar de ser livres.=94
                          (Jean-Paul Sartre)
*
*
*
*
Ao encaminhar/reenviar esta mensagem, por favor:

1. Apague o MEU endere=E7o eletr=F4nico;
2. Apague tamb=E9m os endere=E7os dos amigos;
3. Encaminhe como c=F3pia oculta (Cco ou Bcc) aos SEUS destinat=E1rios.

Agindo sempre assim dificultaremos a dissemina=E7=E3o de v=EDrus, spams e b=
anners.

--=20
Voc=EA recebeu esta mensagem porque voc=EA se inscreveu no lista de dicuss=
=E3o do projeto Arch Linux Brasil - http://groups.google.com/group/archlinu=
x-br=20
Maiores informa=E7=F5es e novidades sobre o projeto podem ser vistas em htt=
p://www.archlinux-br.org
Para mandar mensagens para o grupo use o email archlinux-br-/JYPxA39Uh4Ykp1iOSErHA@public.gmane.org=
m. Lembre-se que somente membros podem postar mensagens.
Para se desinscrever deste grupo, envie um email para archlinux-br-unsubscr=
ibe-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org
Para mais op=E7=F5es. visite este grupo em http://groups.google.com/group/a=
rchlinux-br
--14dae93997ddfca18704b597594a
Content-Type: text/html; charset=windows-1252
Content-Transfer-Encoding: quoted-printable

Pessoal,<div><br></div><div>H=E1 algum problema em aumentar a parti=E7=E3o =
/ ap=F3s o sistema est=E1 todo configurado?</div><div>Acabei colocando muit=
o pouco espa=E7o para a raiz j=E1 que em tese eu iria formatar novamente po=
r=E9m acabei ficando com &quot;pregui=E7a&quot; e deixei da forma que est=
=E1.</div>

<div><br></div><div><div>k ~ $ df -h =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =
=A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0=
 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =
=A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0=
 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =
=A0 =A0 =A0 =A0 =A0 =A0 =A0=A0</div>

<div>Sist. Arq. =A0 =A0 =A0 Tam =A0Usad Dispon. Uso% Montado em =A0 =A0 =A0=
 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =
=A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0=
 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =
=A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0</div><div>rootfs =A0 =
=A0 =A0 =A0 =A07,3G =A06,4G =A0 =A0542M =A093% / =A0 =A0 =A0 =A0 =A0 =A0 =
=A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0=
 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =
=A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0=
 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0=A0</div>

<div>udev =A0 =A0 =A0 =A0 =A0 =A0 10M =A0 =A0 0 =A0 =A0 10M =A0 0% /dev =A0=
 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =
=A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0=
 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =
=A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0</di=
v><div>/run =A0 =A0 =A0 =A0 =A0 =A0 10M =A0308K =A0 =A09,7M =A0 4% /run =A0=
 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =
=A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0=
 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =
=A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0</di=
v>

<div>/dev/sda3 =A0 =A0 =A0 7,3G =A06,4G =A0 =A0542M =A093% / =A0 =A0 =A0 =
=A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0=
 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =
=A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0=
 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0=A0</div><d=
iv>shm =A0 =A0 =A0 =A0 =A0 =A0 1,9G =A0452K =A0 =A01,9G =A0 1% /dev/shm =A0=
 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =
=A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0=
 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =
=A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0</div>

<div>tmpfs =A0 =A0 =A0 =A0 =A0 1,9G =A0200K =A0 =A01,9G =A0 1% /tmp =A0 =A0=
 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =
=A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0=
 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =
=A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0</div><d=
iv>/dev/sda4 =A0 =A0 =A0 451G =A0133G =A0 =A0296G =A031% /home =A0 =A0 =A0 =
=A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0=
 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =
=A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0=
 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0=A0</div>

<div>/dev/sda1 =A0 =A0 =A0 =A099M =A0 18M =A0 =A0 77M =A019% /boot =A0 =A0 =
=A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0=
 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =
=A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0=
 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0=A0</div><div>k=
 ~ $ =A0 =A0</div>

<div><br></div><div>Obrigado.</div><div><br></div>-- <br><div style=3D"text=
-align:left"><div style=3D"text-align:left"><span>Este e-mail pode conter a=
nexos no formato ODF, um</span><span>=A0</span></div><span><div style=3D"te=
xt-align:left">

padr=E3o aberto, gratuito e homologado pela ISO e=A0</div></span><span><div=
 style=3D"text-align:left">ABNT. Para visualizar ou editar, fa=E7a o downlo=
ad em=A0</div></span><div><a href=3D"http://broffice.org/download" style=3D=
"color:rgb(17,85,204)" target=3D"_blank">http://broffice.org/download</a><s=
pan style=3D"color:rgb(34,34,34)">=A0e instale.</span></div>

<div style=3D"text-align:left"><span style=3D"color:rgb(34,34,34);font-fami=
ly:arial,sans-serif"><br></span></div><span><div style=3D"text-align:center=
">&quot;...n=F3s n=E3o somos livres para deixar de ser livres.=94=A0</div><=
/span><span><div style=3D"text-align:center">

=A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0 (Jean-Paul Sartre)</div=
></span></div><div style=3D"text-align:center"><span style=3D"font-family:h=
elvetica,arial,sans-serif;font-size:14px;line-height:15px"><b><br></b></spa=
n></div><div style=3D"text-align:center">

<span style=3D"font-family:helvetica,arial,sans-serif;font-size:14px;line-h=
eight:15px"><b><br></b></span></div><div style=3D"text-align:center"><font =
face=3D"helvetica, arial, sans-serif"><span style=3D"line-height:15px"><div=
 style=3D"text-align:left">

<font size=3D"1">Ao encaminhar/reenviar esta mensagem, por favor:</font></d=
iv><div style=3D"text-align:left"><font size=3D"1"><br></font></div><div st=
yle=3D"text-align:left"><font size=3D"1">1. Apague o MEU endere=E7o eletr=
=F4nico;</font></div>

<div style=3D"text-align:left"><font size=3D"1">2. Apague tamb=E9m os ender=
e=E7os dos amigos;</font></div><div style=3D"text-align:left"><font size=3D=
"1">3. Encaminhe como c=F3pia oculta (Cco ou Bcc) aos SEUS destinat=E1rios.=
</font></div>

<div style=3D"text-align:left"><font size=3D"1"><br></font></div><div style=
=3D"text-align:left"><font size=3D"1">Agindo sempre assim dificultaremos a =
dissemina=E7=E3o de v=EDrus, spams e banners.</font></div><div style=3D"fon=
t-size:14px;text-align:left">

<br></div></span></font></div><br>
</div>

<p></p>

-- <br />
Voc=EA recebeu esta mensagem porque voc=EA se inscreveu no lista de dicuss=
=E3o do projeto Arch Linux Brasil - <a href=3D"http://groups.google.com/gro=
up/archlinux-br">http://groups.google.com/group/archlinux-br</a> <br />
Maiores informa=E7=F5es e novidades sobre o projeto podem ser vistas em <a =
href=3D"http://www.archlinux-br.org">http://www.archlinux-br.org</a><br />
Para mandar mensagens para o grupo use o email archlinux-br-/JYPxA39Uh4Ykp1iOSErHA@public.gmane.org=
m. Lembre-se que somente membros podem postar mensagens.<br />
Para se desinscrever deste grupo, envie um email para archlinux-br-unsubscr=
ibe-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org<br />
Para mais op=E7=F5es. visite este grupo em <a href=3D"http://groups.google.=
com/group/archlinux-br">http://groups.google.com/group/archlinux-br</a>
--14dae93997ddfca18704b597594a--

