Path: news.gmane.org!not-for-mail
From: Reinaldo <reinaldocezar-Re5JQEeQqe8AvxtiuMwx3w@public.gmane.org>
Newsgroups: gmane.linux.arch.brazil
Subject: teclado para usuario adicionado
Date: Wed, 28 Dec 2011 19:33:01 -0800 (PST)
Lines: 20
Approved: news@gmane.org
Message-ID: <e0268ec1-4361-48bd-a8e9-9864c88373fb@l24g2000yqm.googlegroups.com>
Reply-To: archlinux-br-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org
NNTP-Posting-Host: lo.gmane.org
Mime-Version: 1.0
Content-Type: text/plain; charset=ISO-8859-1
Content-Transfer-Encoding: quoted-printable
X-Trace: dough.gmane.org 1325154812 21411 80.91.229.12 (29 Dec 2011 10:33:32 GMT)
X-Complaints-To: usenet@dough.gmane.org
NNTP-Posting-Date: Thu, 29 Dec 2011 10:33:32 +0000 (UTC)
To: archlinux-br <archlinux-br-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>
Original-X-From: archlinux-br+bncCMW94YS7ARDsg_H3BBoEjoHoXg-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org Thu Dec 29 11:33:27 2011
Return-path: <archlinux-br+bncCMW94YS7ARDsg_H3BBoEjoHoXg-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>
Envelope-to: glab-archlinux-br@m.gmane.org
Original-Received: from mail-qy0-f186.google.com ([209.85.216.186])
	by lo.gmane.org with esmtp (Exim 4.69)
	(envelope-from <archlinux-br+bncCMW94YS7ARDsg_H3BBoEjoHoXg-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>)
	id 1RgDId-0004oh-1q
	for glab-archlinux-br@m.gmane.org; Thu, 29 Dec 2011 11:33:27 +0100
Original-Received: by qcsg15 with SMTP id g15sf21829362qcs.3
        for <glab-archlinux-br@m.gmane.org>; Thu, 29 Dec 2011 02:33:26 -0800 (PST)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=googlegroups.com; s=beta;
        h=x-beenthere:mime-version:date:user-agent:x-http-useragent
         :message-id:subject:from:to:x-original-sender
         :x-original-authentication-results:reply-to:precedence:mailing-list
         :list-id:x-google-group-id:list-post:list-help:list-archive:sender
         :list-subscribe:list-unsubscribe:content-type
         :content-transfer-encoding;
        bh=j+c4zTWZxH4HuWUD3rjZ5hb0L1WYbystbfXSmquwbtg=;
        b=Sa50JpSE7hkUu7bOPPYau8lxWBe82Je88nsJZ99n0M5FrA36LRCLYMCb0UKZlNiZoY
         NZJ5vIoCajMGPd7hYQqC33VRPWM4W1PghYnpN5W0xbm1LfDFX80uCLBW49BvnBZAuohl
         bs7y+VN3bE0dxAMNV+CmIUArNoUu2euKkg8JI=
Original-Received: by 10.224.216.132 with SMTP id hi4mr6202780qab.9.1325154796821;
        Thu, 29 Dec 2011 02:33:16 -0800 (PST)
X-BeenThere: archlinux-br-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org
Original-Received: by 10.229.166.138 with SMTP id m10ls1671215qcy.3.gmail; Thu, 29 Dec
 2011 02:33:15 -0800 (PST)
Original-Received: by 10.224.180.2 with SMTP id bs2mr72236469qab.1.1325154795485;
        Thu, 29 Dec 2011 02:33:15 -0800 (PST)
Original-Received: by 10.224.176.134 with SMTP id be6msqab;
        Wed, 28 Dec 2011 19:33:01 -0800 (PST)
Original-Received: by 10.52.67.172 with SMTP id o12mr4243678vdt.18.1325129581146; Wed,
 28 Dec 2011 19:33:01 -0800 (PST)
Original-Received: by l24g2000yqm.googlegroups.com with HTTP; Wed, 28 Dec 2011 19:33:01
 -0800 (PST)
User-Agent: G2/1.0
X-HTTP-UserAgent: Mozilla/5.0 (X11; Linux x86_64; rv:8.0.1) Gecko/20100101 Firefox/8.0.1,gzip(gfe)
X-Original-Sender: reinaldocezar-Re5JQEeQqe8AvxtiuMwx3w@public.gmane.org
X-Original-Authentication-Results: ls.google.com; spf=pass (google.com: domain
 of reinaldocezar-Re5JQEeQqe8AvxtiuMwx3w@public.gmane.org designates internal as permitted sender)
 smtp.mail=reinaldocezar-Re5JQEeQqe8AvxtiuMwx3w@public.gmane.org; dkim=pass header.i=@gmail.com
Precedence: list
Mailing-list: list archlinux-br-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org; contact archlinux-br+owners-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org
List-ID: <archlinux-br.googlegroups.com>
X-Google-Group-Id: 926417450308
List-Post: <http://groups.google.com/group/archlinux-br/post?hl=pt-BR_US>, <mailto:archlinux-br-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>
List-Help: <http://groups.google.com/support/?hl=pt-BR_US>, <mailto:archlinux-br+help-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>
List-Archive: <http://groups.google.com/group/archlinux-br?hl=pt-BR_US>
Original-Sender: archlinux-br-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org
List-Subscribe: <http://groups.google.com/group/archlinux-br/subscribe?hl=pt-BR_US>,
 <mailto:archlinux-br+subscribe-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>
List-Unsubscribe: <http://groups.google.com/group/archlinux-br/subscribe?hl=pt-BR_US>,
 <mailto:archlinux-br+unsubscribe-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>
Xref: news.gmane.org gmane.linux.arch.brazil:6204
Archived-At: <http://permalink.gmane.org/gmane.linux.arch.brazil/6204>

Prezados,
criei um usuario e nao estou conseguindo configurar o teclado dele.
Tanto o rc.conf como o locale.gen estao com as opcoes corretas.

Alguem pode me ajudar?
Obrigado.

--=20
Voc=EA recebeu esta mensagem porque voc=EA se inscreveu no lista de dicuss=
=E3o do projeto Arch Linux Brasil - http://groups.google.com/group/archlinu=
x-br=20
Maiores informa=E7=F5es e novidades sobre o projeto podem ser vistas em htt=
p://www.archlinux-br.org
Para mandar mensagens para o grupo use o email archlinux-br-/JYPxA39Uh4Ykp1iOSErHA@public.gmane.org=
m. Lembre-se que somente membros podem postar mensagens.
Para se desinscrever deste grupo, envie um email para archlinux-br-unsubscr=
ibe-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org
Para mais op=E7=F5es. visite este grupo em http://groups.google.com/group/a=
rchlinux-br

