Path: news.gmane.org!not-for-mail
From: =?utf-8?B?UmljYXJkbyDMvQ==?= <ricardocash-PkbjNfxxIARBDgjK7y7TUQ@public.gmane.org>
Newsgroups: gmane.linux.arch.brazil
Subject: =?ISO-8859-1?Q?=5Barchlinux=2Dbr=5D_Ultimas_Atualiza=E7=F5es?=
Date: Wed, 21 Dec 2011 01:04:25 +0300
Lines: 65
Approved: news@gmane.org
Message-ID: <SNT125-W59E289517E98BA16634C6B6A40@phx.gbl>
Reply-To: archlinux-br-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org
NNTP-Posting-Host: lo.gmane.org
Mime-Version: 1.0
Content-Type: multipart/alternative;
	boundary="_723da825-2007-4049-9113-ec69908b8c04_"
X-Trace: dough.gmane.org 1324418694 2696 80.91.229.12 (20 Dec 2011 22:04:54 GMT)
X-Complaints-To: usenet@dough.gmane.org
NNTP-Posting-Date: Tue, 20 Dec 2011 22:04:54 +0000 (UTC)
To: <archlinux-br-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>
Original-X-From: archlinux-br+bncCPfo1Iu_DRDrjMT3BBoEI1DAVw-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org Tue Dec 20 23:04:48 2011
Return-path: <archlinux-br+bncCPfo1Iu_DRDrjMT3BBoEI1DAVw-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>
Envelope-to: glab-archlinux-br@m.gmane.org
Original-Received: from mail-gx0-f186.google.com ([209.85.161.186])
	by lo.gmane.org with esmtp (Exim 4.69)
	(envelope-from <archlinux-br+bncCPfo1Iu_DRDrjMT3BBoEI1DAVw-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>)
	id 1Rd7nZ-00073G-7g
	for glab-archlinux-br@m.gmane.org; Tue, 20 Dec 2011 23:04:37 +0100
Original-Received: by ggnk1 with SMTP id k1sf7012090ggn.3
        for <glab-archlinux-br@m.gmane.org>; Tue, 20 Dec 2011 14:04:36 -0800 (PST)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=googlegroups.com; s=beta;
        h=x-beenthere:received-spf:message-id:x-originating-ip:from:to
         :subject:date:importance:mime-version:x-originalarrivaltime
         :x-original-sender:x-original-authentication-results:reply-to
         :precedence:mailing-list:list-id:x-google-group-id:list-post
         :list-help:list-archive:sender:list-subscribe:list-unsubscribe
         :content-type;
        bh=HgLVrB5gvUoqdVbGgJ0pJxM8RBY9eoLJXwJ+qiYUaA8=;
        b=D7TxfpX9xzzp/+jXTfx8WzfxyLXKour1nI2Y5+NGPBV6QgoDpS9d0QPLzxOxPAaX12
         vNnUDcZ/e/HIRNACF/WqiqyU94C32N9gfYUu4HYXGZAlOPfaQNz5yJ6CYsO+/N7TQ1oR
         XkAIAVSh0x5hzmdoEhcNT2ELjqE8j/RgwIToQ=
Original-Received: by 10.236.176.103 with SMTP id a67mr1137991yhm.7.1324418667047;
        Tue, 20 Dec 2011 14:04:27 -0800 (PST)
X-BeenThere: archlinux-br-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org
Original-Received: by 10.101.163.1 with SMTP id q1ls5040090ano.3.gmail; Tue, 20 Dec
 2011 14:04:26 -0800 (PST)
Original-Received: by 10.101.197.40 with SMTP id z40mr2301107anp.5.1324418666163;
        Tue, 20 Dec 2011 14:04:26 -0800 (PST)
Original-Received: by 10.101.197.40 with SMTP id z40mr2301104anp.5.1324418666142;
        Tue, 20 Dec 2011 14:04:26 -0800 (PST)
Original-Received: from snt0-omc3-s28.snt0.hotmail.com (snt0-omc3-s28.snt0.hotmail.com. [65.55.90.167])
        by gmr-mx.google.com with ESMTP id w48si1399540yhk.4.2011.12.20.14.04.25;
        Tue, 20 Dec 2011 14:04:26 -0800 (PST)
Received-SPF: pass (google.com: domain of ricardocash-PkbjNfxxIARBDgjK7y7TUQ@public.gmane.org designates 65.55.90.167 as permitted sender) client-ip=65.55.90.167;
Original-Received: from SNT125-W5 ([65.55.90.136]) by snt0-omc3-s28.snt0.hotmail.com with Microsoft SMTPSVC(6.0.3790.4675);
	 Tue, 20 Dec 2011 14:04:25 -0800
X-Originating-IP: [187.79.54.211]
Importance: Normal
X-OriginalArrivalTime: 20 Dec 2011 22:04:25.0763 (UTC) FILETIME=[564FA730:01CCBF63]
X-Original-Sender: ricardocash-PkbjNfxxIARBDgjK7y7TUQ@public.gmane.org
X-Original-Authentication-Results: gmr-mx.google.com; spf=pass (google.com:
 domain of ricardocash-PkbjNfxxIARBDgjK7y7TUQ@public.gmane.org designates 65.55.90.167 as permitted
 sender) smtp.mail=ricardocash-PkbjNfxxIARBDgjK7y7TUQ@public.gmane.org
Precedence: list
Mailing-list: list archlinux-br-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org; contact archlinux-br+owners-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org
List-ID: <archlinux-br.googlegroups.com>
X-Google-Group-Id: 926417450308
List-Post: <http://groups.google.com/group/archlinux-br/post?hl=pt-BR_US>, <mailto:archlinux-br-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>
List-Help: <http://groups.google.com/support/?hl=pt-BR_US>, <mailto:archlinux-br+help-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>
List-Archive: <http://groups.google.com/group/archlinux-br?hl=pt-BR_US>
Original-Sender: archlinux-br-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org
List-Subscribe: <http://groups.google.com/group/archlinux-br/subscribe?hl=pt-BR_US>,
 <mailto:archlinux-br+subscribe-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>
List-Unsubscribe: <http://groups.google.com/group/archlinux-br/subscribe?hl=pt-BR_US>,
 <mailto:archlinux-br+unsubscribe-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org>
Xref: news.gmane.org gmane.linux.arch.brazil:6193
Archived-At: <http://permalink.gmane.org/gmane.linux.arch.brazil/6193>

--_723da825-2007-4049-9113-ec69908b8c04_
Content-Type: text/plain; charset=ISO-8859-1
Content-Transfer-Encoding: quoted-printable


erro: falha ao submeter a transa=E7=E3o (arquivos conflitantes)
filesystem: /etc/mtab existe no sistema de arquivos
Ocorreram erros, nenhum pacote foi atualizado.

fui atualizar o arch.. qnd vai instalar os pacote da esse erro..
 		 	   		 =20

--=20
Voc=EA recebeu esta mensagem porque voc=EA se inscreveu no lista de dicuss=
=E3o do projeto Arch Linux Brasil - http://groups.google.com/group/archlinu=
x-br=20
Maiores informa=E7=F5es e novidades sobre o projeto podem ser vistas em htt=
p://www.archlinux-br.org
Para mandar mensagens para o grupo use o email archlinux-br-/JYPxA39Uh4Ykp1iOSErHA@public.gmane.org=
m. Lembre-se que somente membros podem postar mensagens.
Para se desinscrever deste grupo, envie um email para archlinux-br-unsubscr=
ibe-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org
Para mais op=E7=F5es. visite este grupo em http://groups.google.com/group/a=
rchlinux-br
--_723da825-2007-4049-9113-ec69908b8c04_
Content-Type: text/html; charset=ISO-8859-1
Content-Transfer-Encoding: quoted-printable

<html>
<head>
<style><!--
.hmmessage P
{
margin:0px;
padding:0px
}
body.hmmessage
{
font-size: 10pt;
font-family:Tahoma
}
--></style></head>
<body class=3D'hmmessage'><div dir=3D'ltr'>
erro: falha ao submeter a transa=E7=E3o (arquivos conflitantes)<br>filesyst=
em: /etc/mtab existe no sistema de arquivos<br>Ocorreram erros, nenhum paco=
te foi atualizado.<br><br>fui atualizar o arch.. qnd vai instalar os pacote=
 da esse erro..<br> 		 	   		  </div></body>
</html>

<p></p>

-- <br />
Voc=EA recebeu esta mensagem porque voc=EA se inscreveu no lista de dicuss=
=E3o do projeto Arch Linux Brasil - <a href=3D"http://groups.google.com/gro=
up/archlinux-br">http://groups.google.com/group/archlinux-br</a> <br />
Maiores informa=E7=F5es e novidades sobre o projeto podem ser vistas em <a =
href=3D"http://www.archlinux-br.org">http://www.archlinux-br.org</a><br />
Para mandar mensagens para o grupo use o email archlinux-br-/JYPxA39Uh4Ykp1iOSErHA@public.gmane.org=
m. Lembre-se que somente membros podem postar mensagens.<br />
Para se desinscrever deste grupo, envie um email para archlinux-br-unsubscr=
ibe-/JYPxA39Uh5TLH3MbocFFw@public.gmane.org<br />
Para mais op=E7=F5es. visite este grupo em <a href=3D"http://groups.google.=
com/group/archlinux-br">http://groups.google.com/group/archlinux-br</a>
--_723da825-2007-4049-9113-ec69908b8c04_--

