Path: news.gmane.org!not-for-mail
From: unknown <post@gwene.org>
Newsgroups: gwene.linux.archlinux.packages
Subject: upx 3.08-1 x86_64
Date: Fri, 16 Dec 2011 21:02:54 +0100
Lines: 2
Approved: news@gmane.org
Message-ID: <x1-Z3sr77rPLVdSTfpfgqS5+6lZ+iA@gwene.org>
NNTP-Posting-Host: sea.gmane.org
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: 8bit
X-Trace: dough.gmane.org 1324067117 6055 80.91.229.5 (16 Dec 2011 20:25:17 GMT)
X-Complaints-To: usenet@dough.gmane.org
NNTP-Posting-Date: Fri, 16 Dec 2011 20:25:17 +0000 (UTC)
X-Content-Hash: FZ+VoN8YOXMkwMdcyhyjFjaIBqI
X-Feed: http://www.archlinux.org/feeds/packages/
Archived-at: <http://www.archlinux.org/packages/community/x86_64/upx/>
Xref: news.gmane.org gwene.linux.archlinux.packages:31947

Ultimate executable compressor.
<p><a href="http://www.archlinux.org/packages/community/x86_64/upx/">Link</a>
