#!/bin/sh

ICEWM_PRIVCFG=$HOME/.icewm2 icewm --display=$DISPLAY.1 &
export XAUTHORITY=~/.Xauthority &

## DD=${DISPLAY:1:1} &                                           # find out if VT 7 or 8

sleep 3

/usr/bin/xsettingsd &
start-pulseaudio-x11 &

alsactl -f /root/local/asound.state restore &
# Switch off Nautilus meddling with the Desktop
#gconftool-2 -s -t bool /apps/nautilus/preferences/show_desktop false &
#gconftool-2 -s -t bool /desktop/gnome/background/draw_background false &

export DE=gnome # to foul xdg-open

xmodmap ~/.Xmodmap  &
tmux kill-server

xbindkeys &
xhost + &
idesk &
udiskie &
gkrellm &
#autocutsel -fork &
autocutsel -selection PRIMARY -fork &
nitrogen --restore &
adeskbar firstscreen &
xcompmgr &
#devilspie &
(sleep 5; sakura -c 110 -r 28 -n 4 --geometry 110x28+82+23) &

#vncserver -geometry 1680x1050 :1 &
#x11vnc -forever -usepw &
#(hamachi start; hamachi get-nicks) &

/usr/bin/xset r rate 300 20 &
#xset m 2 0 &
xset s 1800 &
xset dpms 1800 1800 1800 &
xset -b &

(sleep 8; aplay /opt/MyDocs/Sounds/katapum.wav) &
# 2nd screen  ---------------------------------------------------------------------------

  DISPLAY=$DISPLAY.1 icewmtray &
  sleep 5
  DISPLAY=$DISPLAY.1 /usr/bin/synergys &
  DISPLAY=$DISPLAY.1 /usr/bin/adeskbar &
  DISPLAY=$DISPLAY.1 archassistant &
  DISPLAY=$DISPLAY.1 /usr/bin/dropboxd &
  DISPLAY=$DISPLAY.1 checkgmail -no_cookies &
# DISPLAY=$DISPLAY.1 LANG=pt_PT.UTF-8 gnote --note-path=/root/Dropbox/Gnote &
  (sleep 180; DISPLAY=$DISPLAY.1 gnote --note-path=/root/Dropbox/Gnote) &
  DISPLAY=$DISPLAY.1 /root/bin/idesk2 &
  DISPLAY=$DISPLAY.1 /usr/bin/gvolwheel &
  DISPLAY=$DISPLAY.1 /usr/bin/qwit &
  DISPLAY=$DISPLAY.1 nitrogen --restore &
  DISPLAY=$DISPLAY.1 /usr/bin/xcompmgr &
  DISPLAY=$DISPLAY.1 Terminal --geometry=122x30+333+350 --hide-menubar \
	                          -T Everything --command "tail -f /var/log/everything.log" \
			                  --tab -T "Shell 1" --tab -T "Shell 2" --tab -T "Shell 3" --tab -T "Shell 4" &
  (sleep 30; LC_ALL=en_IE.utf-8  DISPLAY=$DISPLAY.1 /usr/bin/conky -c /root/Conky/conkyCalendar/conkyrc) &

# 2nd screen - END ----------------------------------------------------------------------
